// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
enum ConnectionStateEnum : int {
  CONNECTION_STATE_DISCONNECTED = 0,
  CONNECTION_STATE_CONNECTING = 1,
  CONNECTION_STATE_CONNECTED = 2,
  CONNECTION_STATE_DISCONNECTING = 3,
};

bool ConnectionStateEnum_IsValid(int value);
extern const uint32_t ConnectionStateEnum_internal_data_[];
constexpr ConnectionStateEnum ConnectionStateEnum_MIN = static_cast<ConnectionStateEnum>(0);
constexpr ConnectionStateEnum ConnectionStateEnum_MAX = static_cast<ConnectionStateEnum>(3);
constexpr int ConnectionStateEnum_ARRAYSIZE = 3 + 1;
const std::string& ConnectionStateEnum_Name(ConnectionStateEnum value);
template <typename T>
const std::string& ConnectionStateEnum_Name(T value) {
  static_assert(std::is_same<T, ConnectionStateEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ConnectionStateEnum_Name().");
  return ConnectionStateEnum_Name(static_cast<ConnectionStateEnum>(value));
}
const std::string& ConnectionStateEnum_Name(ConnectionStateEnum value);
bool ConnectionStateEnum_Parse(absl::string_view name, ConnectionStateEnum* value);
enum EnableDisableReasonEnum : int {
  ENABLE_DISABLE_REASON_UNSPECIFIED = 0,
  ENABLE_DISABLE_REASON_APPLICATION_REQUEST = 1,
  ENABLE_DISABLE_REASON_AIRPLANE_MODE = 2,
  ENABLE_DISABLE_REASON_DISALLOWED = 3,
  ENABLE_DISABLE_REASON_RESTARTED = 4,
  ENABLE_DISABLE_REASON_START_ERROR = 5,
  ENABLE_DISABLE_REASON_SYSTEM_BOOT = 6,
  ENABLE_DISABLE_REASON_CRASH = 7,
  ENABLE_DISABLE_REASON_USER_SWITCH = 8,
  ENABLE_DISABLE_REASON_RESTORE_USER_SETTING = 9,
  ENABLE_DISABLE_REASON_FACTORY_RESET = 10,
  ENABLE_DISABLE_REASON_INIT_FLAGS_CHANGED = 11,
  ENABLE_DISABLE_REASON_SATELLITE_MODE = 12,
  ENABLE_DISABLE_REASON_APPLICATION_DIED = 13,
  ENABLE_DISABLE_REASON_AUTO_ON = 14,
};

bool EnableDisableReasonEnum_IsValid(int value);
extern const uint32_t EnableDisableReasonEnum_internal_data_[];
constexpr EnableDisableReasonEnum EnableDisableReasonEnum_MIN = static_cast<EnableDisableReasonEnum>(0);
constexpr EnableDisableReasonEnum EnableDisableReasonEnum_MAX = static_cast<EnableDisableReasonEnum>(14);
constexpr int EnableDisableReasonEnum_ARRAYSIZE = 14 + 1;
const std::string& EnableDisableReasonEnum_Name(EnableDisableReasonEnum value);
template <typename T>
const std::string& EnableDisableReasonEnum_Name(T value) {
  static_assert(std::is_same<T, EnableDisableReasonEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnableDisableReasonEnum_Name().");
  return EnableDisableReasonEnum_Name(static_cast<EnableDisableReasonEnum>(value));
}
const std::string& EnableDisableReasonEnum_Name(EnableDisableReasonEnum value);
bool EnableDisableReasonEnum_Parse(absl::string_view name, EnableDisableReasonEnum* value);
enum DirectionEnum : int {
  DIRECTION_UNKNOWN = 0,
  DIRECTION_OUTGOING = 1,
  DIRECTION_INCOMING = 2,
};

bool DirectionEnum_IsValid(int value);
extern const uint32_t DirectionEnum_internal_data_[];
constexpr DirectionEnum DirectionEnum_MIN = static_cast<DirectionEnum>(0);
constexpr DirectionEnum DirectionEnum_MAX = static_cast<DirectionEnum>(2);
constexpr int DirectionEnum_ARRAYSIZE = 2 + 1;
const std::string& DirectionEnum_Name(DirectionEnum value);
template <typename T>
const std::string& DirectionEnum_Name(T value) {
  static_assert(std::is_same<T, DirectionEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DirectionEnum_Name().");
  return DirectionEnum_Name(static_cast<DirectionEnum>(value));
}
const std::string& DirectionEnum_Name(DirectionEnum value);
bool DirectionEnum_Parse(absl::string_view name, DirectionEnum* value);
enum LinkTypeEnum : int {
  LINK_TYPE_UNKNOWN = 4095,
  LINK_TYPE_SCO = 0,
  LINK_TYPE_ACL = 1,
  LINK_TYPE_ESCO = 2,
};

bool LinkTypeEnum_IsValid(int value);
extern const uint32_t LinkTypeEnum_internal_data_[];
constexpr LinkTypeEnum LinkTypeEnum_MIN = static_cast<LinkTypeEnum>(0);
constexpr LinkTypeEnum LinkTypeEnum_MAX = static_cast<LinkTypeEnum>(4095);
constexpr int LinkTypeEnum_ARRAYSIZE = 4095 + 1;
const std::string& LinkTypeEnum_Name(LinkTypeEnum value);
template <typename T>
const std::string& LinkTypeEnum_Name(T value) {
  static_assert(std::is_same<T, LinkTypeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LinkTypeEnum_Name().");
  return LinkTypeEnum_Name(static_cast<LinkTypeEnum>(value));
}
const std::string& LinkTypeEnum_Name(LinkTypeEnum value);
bool LinkTypeEnum_Parse(absl::string_view name, LinkTypeEnum* value);
enum DeviceInfoSrcEnum : int {
  DEVICE_INFO_SRC_UNKNOWN = 0,
  DEVICE_INFO_INTERNAL = 1,
  DEVICE_INFO_EXTERNAL = 2,
};

bool DeviceInfoSrcEnum_IsValid(int value);
extern const uint32_t DeviceInfoSrcEnum_internal_data_[];
constexpr DeviceInfoSrcEnum DeviceInfoSrcEnum_MIN = static_cast<DeviceInfoSrcEnum>(0);
constexpr DeviceInfoSrcEnum DeviceInfoSrcEnum_MAX = static_cast<DeviceInfoSrcEnum>(2);
constexpr int DeviceInfoSrcEnum_ARRAYSIZE = 2 + 1;
const std::string& DeviceInfoSrcEnum_Name(DeviceInfoSrcEnum value);
template <typename T>
const std::string& DeviceInfoSrcEnum_Name(T value) {
  static_assert(std::is_same<T, DeviceInfoSrcEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DeviceInfoSrcEnum_Name().");
  return DeviceInfoSrcEnum_Name(static_cast<DeviceInfoSrcEnum>(value));
}
const std::string& DeviceInfoSrcEnum_Name(DeviceInfoSrcEnum value);
bool DeviceInfoSrcEnum_Parse(absl::string_view name, DeviceInfoSrcEnum* value);
enum DeviceTypeEnum : int {
  DEVICE_TYPE_UNKNOWN = 0,
  DEVICE_TYPE_CLASSIC = 1,
  DEVICE_TYPE_LE = 2,
  DEVICE_TYPE_DUAL = 3,
};

bool DeviceTypeEnum_IsValid(int value);
extern const uint32_t DeviceTypeEnum_internal_data_[];
constexpr DeviceTypeEnum DeviceTypeEnum_MIN = static_cast<DeviceTypeEnum>(0);
constexpr DeviceTypeEnum DeviceTypeEnum_MAX = static_cast<DeviceTypeEnum>(3);
constexpr int DeviceTypeEnum_ARRAYSIZE = 3 + 1;
const std::string& DeviceTypeEnum_Name(DeviceTypeEnum value);
template <typename T>
const std::string& DeviceTypeEnum_Name(T value) {
  static_assert(std::is_same<T, DeviceTypeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DeviceTypeEnum_Name().");
  return DeviceTypeEnum_Name(static_cast<DeviceTypeEnum>(value));
}
const std::string& DeviceTypeEnum_Name(DeviceTypeEnum value);
bool DeviceTypeEnum_Parse(absl::string_view name, DeviceTypeEnum* value);
enum TransportTypeEnum : int {
  TRANSPORT_TYPE_AUTO = 0,
  TRANSPORT_TYPE_BREDR = 1,
  TRANSPORT_TYPE_LE = 2,
};

bool TransportTypeEnum_IsValid(int value);
extern const uint32_t TransportTypeEnum_internal_data_[];
constexpr TransportTypeEnum TransportTypeEnum_MIN = static_cast<TransportTypeEnum>(0);
constexpr TransportTypeEnum TransportTypeEnum_MAX = static_cast<TransportTypeEnum>(2);
constexpr int TransportTypeEnum_ARRAYSIZE = 2 + 1;
const std::string& TransportTypeEnum_Name(TransportTypeEnum value);
template <typename T>
const std::string& TransportTypeEnum_Name(T value) {
  static_assert(std::is_same<T, TransportTypeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TransportTypeEnum_Name().");
  return TransportTypeEnum_Name(static_cast<TransportTypeEnum>(value));
}
const std::string& TransportTypeEnum_Name(TransportTypeEnum value);
bool TransportTypeEnum_Parse(absl::string_view name, TransportTypeEnum* value);
enum BondStateEnum : int {
  BOND_STATE_UNKNOWN = 0,
  BOND_STATE_NONE = 10,
  BOND_STATE_BONDING = 11,
  BOND_STATE_BONDED = 12,
};

bool BondStateEnum_IsValid(int value);
extern const uint32_t BondStateEnum_internal_data_[];
constexpr BondStateEnum BondStateEnum_MIN = static_cast<BondStateEnum>(0);
constexpr BondStateEnum BondStateEnum_MAX = static_cast<BondStateEnum>(12);
constexpr int BondStateEnum_ARRAYSIZE = 12 + 1;
const std::string& BondStateEnum_Name(BondStateEnum value);
template <typename T>
const std::string& BondStateEnum_Name(T value) {
  static_assert(std::is_same<T, BondStateEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BondStateEnum_Name().");
  return BondStateEnum_Name(static_cast<BondStateEnum>(value));
}
const std::string& BondStateEnum_Name(BondStateEnum value);
bool BondStateEnum_Parse(absl::string_view name, BondStateEnum* value);
enum BondSubStateEnum : int {
  BOND_SUB_STATE_UNKNOWN = 0,
  BOND_SUB_STATE_LOCAL_OOB_DATA_PROVIDED = 1,
  BOND_SUB_STATE_LOCAL_PIN_REQUESTED = 2,
  BOND_SUB_STATE_LOCAL_PIN_REPLIED = 3,
  BOND_SUB_STATE_LOCAL_SSP_REQUESTED = 4,
  BOND_SUB_STATE_LOCAL_SSP_REPLIED = 5,
  BOND_SUB_STATE_LOCAL_BOND_STATE_INTENT_SENT = 6,
  BOND_SUB_STATE_LOCAL_START_PAIRING = 7,
  BOND_SUB_STATE_LOCAL_START_PAIRING_OOB = 8,
};

bool BondSubStateEnum_IsValid(int value);
extern const uint32_t BondSubStateEnum_internal_data_[];
constexpr BondSubStateEnum BondSubStateEnum_MIN = static_cast<BondSubStateEnum>(0);
constexpr BondSubStateEnum BondSubStateEnum_MAX = static_cast<BondSubStateEnum>(8);
constexpr int BondSubStateEnum_ARRAYSIZE = 8 + 1;
const std::string& BondSubStateEnum_Name(BondSubStateEnum value);
template <typename T>
const std::string& BondSubStateEnum_Name(T value) {
  static_assert(std::is_same<T, BondSubStateEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BondSubStateEnum_Name().");
  return BondSubStateEnum_Name(static_cast<BondSubStateEnum>(value));
}
const std::string& BondSubStateEnum_Name(BondSubStateEnum value);
bool BondSubStateEnum_Parse(absl::string_view name, BondSubStateEnum* value);
enum UnbondReasonEnum : int {
  UNBOND_REASON_UNKNOWN = 0,
  UNBOND_REASON_AUTH_FAILED = 1,
  UNBOND_REASON_AUTH_REJECTED = 2,
  UNBOND_REASON_AUTH_CANCELED = 3,
  UNBOND_REASON_REMOTE_DEVICE_DOWN = 4,
  UNBOND_REASON_DISCOVERY_IN_PROGRESS = 5,
  UNBOND_REASON_AUTH_TIMEOUT = 6,
  UNBOND_REASON_REPEATED_ATTEMPTS = 7,
  UNBOND_REASON_REMOTE_AUTH_CANCELED = 8,
  UNBOND_REASON_REMOVED = 9,
};

bool UnbondReasonEnum_IsValid(int value);
extern const uint32_t UnbondReasonEnum_internal_data_[];
constexpr UnbondReasonEnum UnbondReasonEnum_MIN = static_cast<UnbondReasonEnum>(0);
constexpr UnbondReasonEnum UnbondReasonEnum_MAX = static_cast<UnbondReasonEnum>(9);
constexpr int UnbondReasonEnum_ARRAYSIZE = 9 + 1;
const std::string& UnbondReasonEnum_Name(UnbondReasonEnum value);
template <typename T>
const std::string& UnbondReasonEnum_Name(T value) {
  static_assert(std::is_same<T, UnbondReasonEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to UnbondReasonEnum_Name().");
  return UnbondReasonEnum_Name(static_cast<UnbondReasonEnum>(value));
}
const std::string& UnbondReasonEnum_Name(UnbondReasonEnum value);
bool UnbondReasonEnum_Parse(absl::string_view name, UnbondReasonEnum* value);
enum SocketTypeEnum : int {
  SOCKET_TYPE_UNKNOWN = 0,
  SOCKET_TYPE_RFCOMM = 1,
  SOCKET_TYPE_SCO = 2,
  SOCKET_TYPE_L2CAP_BREDR = 3,
  SOCKET_TYPE_L2CAP_LE = 4,
};

bool SocketTypeEnum_IsValid(int value);
extern const uint32_t SocketTypeEnum_internal_data_[];
constexpr SocketTypeEnum SocketTypeEnum_MIN = static_cast<SocketTypeEnum>(0);
constexpr SocketTypeEnum SocketTypeEnum_MAX = static_cast<SocketTypeEnum>(4);
constexpr int SocketTypeEnum_ARRAYSIZE = 4 + 1;
const std::string& SocketTypeEnum_Name(SocketTypeEnum value);
template <typename T>
const std::string& SocketTypeEnum_Name(T value) {
  static_assert(std::is_same<T, SocketTypeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SocketTypeEnum_Name().");
  return SocketTypeEnum_Name(static_cast<SocketTypeEnum>(value));
}
const std::string& SocketTypeEnum_Name(SocketTypeEnum value);
bool SocketTypeEnum_Parse(absl::string_view name, SocketTypeEnum* value);
enum SocketConnectionstateEnum : int {
  SOCKET_CONNECTION_STATE_UNKNOWN = 0,
  SOCKET_CONNECTION_STATE_LISTENING = 1,
  SOCKET_CONNECTION_STATE_CONNECTING = 2,
  SOCKET_CONNECTION_STATE_CONNECTED = 3,
  SOCKET_CONNECTION_STATE_DISCONNECTING = 4,
  SOCKET_CONNECTION_STATE_DISCONNECTED = 5,
};

bool SocketConnectionstateEnum_IsValid(int value);
extern const uint32_t SocketConnectionstateEnum_internal_data_[];
constexpr SocketConnectionstateEnum SocketConnectionstateEnum_MIN = static_cast<SocketConnectionstateEnum>(0);
constexpr SocketConnectionstateEnum SocketConnectionstateEnum_MAX = static_cast<SocketConnectionstateEnum>(5);
constexpr int SocketConnectionstateEnum_ARRAYSIZE = 5 + 1;
const std::string& SocketConnectionstateEnum_Name(SocketConnectionstateEnum value);
template <typename T>
const std::string& SocketConnectionstateEnum_Name(T value) {
  static_assert(std::is_same<T, SocketConnectionstateEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SocketConnectionstateEnum_Name().");
  return SocketConnectionstateEnum_Name(static_cast<SocketConnectionstateEnum>(value));
}
const std::string& SocketConnectionstateEnum_Name(SocketConnectionstateEnum value);
bool SocketConnectionstateEnum_Parse(absl::string_view name, SocketConnectionstateEnum* value);
enum SocketRoleEnum : int {
  SOCKET_ROLE_UNKNOWN = 0,
  SOCKET_ROLE_LISTEN = 1,
  SOCKET_ROLE_CONNECTION = 2,
};

bool SocketRoleEnum_IsValid(int value);
extern const uint32_t SocketRoleEnum_internal_data_[];
constexpr SocketRoleEnum SocketRoleEnum_MIN = static_cast<SocketRoleEnum>(0);
constexpr SocketRoleEnum SocketRoleEnum_MAX = static_cast<SocketRoleEnum>(2);
constexpr int SocketRoleEnum_ARRAYSIZE = 2 + 1;
const std::string& SocketRoleEnum_Name(SocketRoleEnum value);
template <typename T>
const std::string& SocketRoleEnum_Name(T value) {
  static_assert(std::is_same<T, SocketRoleEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SocketRoleEnum_Name().");
  return SocketRoleEnum_Name(static_cast<SocketRoleEnum>(value));
}
const std::string& SocketRoleEnum_Name(SocketRoleEnum value);
bool SocketRoleEnum_Parse(absl::string_view name, SocketRoleEnum* value);
enum SocketErrorEnum : int {
  SOCKET_ERROR_UNKNOWN = 0,
  SOCKET_ERROR_NONE = 1,
  SOCKET_ERROR_SERVER_START_FAILURE = 2,
  SOCKET_ERROR_CLIENT_INIT_FAILURE = 3,
  SOCKET_ERROR_LISTEN_FAILURE = 4,
  SOCKET_ERROR_CONNECTION_FAILURE = 5,
  SOCKET_ERROR_OPEN_FAILURE = 6,
  SOCKET_ERROR_OFFLOAD_SERVER_NOT_ACCEPTING = 7,
  SOCKET_ERROR_OFFLOAD_HAL_OPEN_FAILURE = 8,
  SOCKET_ERROR_SEND_TO_APP_FAILURE = 9,
  SOCKET_ERROR_RECEIVE_DATA_FAILURE = 10,
  SOCKET_ERROR_READ_SIGNALED_FAILURE = 11,
  SOCKET_ERROR_WRITE_SIGNALED_FAILURE = 12,
  SOCKET_ERROR_SEND_SCN_FAILURE = 13,
  SOCKET_ERROR_SCN_ALLOCATION_FAILURE = 14,
  SOCKET_ERROR_ADD_SDP_FAILURE = 15,
  SOCKET_ERROR_SDP_DISCOVERY_FAILURE = 16,
};

bool SocketErrorEnum_IsValid(int value);
extern const uint32_t SocketErrorEnum_internal_data_[];
constexpr SocketErrorEnum SocketErrorEnum_MIN = static_cast<SocketErrorEnum>(0);
constexpr SocketErrorEnum SocketErrorEnum_MAX = static_cast<SocketErrorEnum>(16);
constexpr int SocketErrorEnum_ARRAYSIZE = 16 + 1;
const std::string& SocketErrorEnum_Name(SocketErrorEnum value);
template <typename T>
const std::string& SocketErrorEnum_Name(T value) {
  static_assert(std::is_same<T, SocketErrorEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SocketErrorEnum_Name().");
  return SocketErrorEnum_Name(static_cast<SocketErrorEnum>(value));
}
const std::string& SocketErrorEnum_Name(SocketErrorEnum value);
bool SocketErrorEnum_Parse(absl::string_view name, SocketErrorEnum* value);
enum L2capCocConnectionResult : int {
  RESULT_L2CAP_CONN_UNKNOWN = 0,
  RESULT_L2CAP_CONN_SUCCESS = 1,
  RESULT_L2CAP_CONN_ACL_FAILURE = 2,
  RESULT_L2CAP_CONN_CL_SEC_FAILURE = 3,
  RESULT_L2CAP_CONN_INSUFFICIENT_AUTHENTICATION = 4,
  RESULT_L2CAP_CONN_INSUFFICIENT_AUTHORIZATION = 5,
  RESULT_L2CAP_CONN_INSUFFICIENT_ENCRYP_KEY_SIZE = 6,
  RESULT_L2CAP_CONN_INSUFFICIENT_ENCRYP = 7,
  RESULT_L2CAP_CONN_INVALID_SOURCE_CID = 8,
  RESULT_L2CAP_CONN_SOURCE_CID_ALREADY_ALLOCATED = 9,
  RESULT_L2CAP_CONN_UNACCEPTABLE_PARAMETERS = 10,
  RESULT_L2CAP_CONN_INVALID_PARAMETERS = 11,
  RESULT_L2CAP_CONN_NO_RESOURCES = 12,
  RESULT_L2CAP_CONN_NO_PSM = 13,
  RESULT_L2CAP_CONN_TIMEOUT = 14,
  RESULT_L2CAP_CONN_BLUETOOTH_OFF = 15,
  RESULT_L2CAP_CONN_BLUETOOTH_SOCKET_CONNECTION_FAILED = 1000,
  RESULT_L2CAP_CONN_BLUETOOTH_SOCKET_CONNECTION_CLOSED = 1001,
  RESULT_L2CAP_CONN_BLUETOOTH_UNABLE_TO_SEND_RPC = 1002,
  RESULT_L2CAP_CONN_BLUETOOTH_NULL_BLUETOOTH_DEVICE = 1003,
  RESULT_L2CAP_CONN_BLUETOOTH_GET_SOCKET_MANAGER_FAILED = 1004,
  RESULT_L2CAP_CONN_BLUETOOTH_NULL_FILE_DESCRIPTOR = 1005,
  RESULT_L2CAP_CONN_SERVER_FAILURE = 2000,
};

bool L2capCocConnectionResult_IsValid(int value);
extern const uint32_t L2capCocConnectionResult_internal_data_[];
constexpr L2capCocConnectionResult L2capCocConnectionResult_MIN = static_cast<L2capCocConnectionResult>(0);
constexpr L2capCocConnectionResult L2capCocConnectionResult_MAX = static_cast<L2capCocConnectionResult>(2000);
constexpr int L2capCocConnectionResult_ARRAYSIZE = 2000 + 1;
const std::string& L2capCocConnectionResult_Name(L2capCocConnectionResult value);
template <typename T>
const std::string& L2capCocConnectionResult_Name(T value) {
  static_assert(std::is_same<T, L2capCocConnectionResult>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to L2capCocConnectionResult_Name().");
  return L2capCocConnectionResult_Name(static_cast<L2capCocConnectionResult>(value));
}
const std::string& L2capCocConnectionResult_Name(L2capCocConnectionResult value);
bool L2capCocConnectionResult_Parse(absl::string_view name, L2capCocConnectionResult* value);
enum CodePathCounterKeyEnum : int {
  COUNTER_KEY_UNKNOWN = 0,
  L2CAP_SUCCESS = 100000,
  L2CAP_CONNECT_CONFIRM_NEG = 100001,
  L2CAP_NO_COMPATIBLE_CHANNEL_AT_CSM_CLOSED = 100002,
  L2CAP_SECURITY_NEG_AT_CSM_CLOSED = 100003,
  L2CAP_TIMEOUT_AT_CSM_CLOSED = 100004,
  L2CAP_CREDIT_BASED_CONNECT_RSP_NEG = 100005,
  L2CAP_CONNECT_RSP_NEG = 100006,
  L2CAP_INFO_NO_COMPATIBLE_CHANNEL_AT_RSP = 100007,
  L2CAP_CONFIG_REQ_FAILURE = 100008,
  L2CAP_CONFIG_RSP_NEG = 100009,
  L2CAP_NO_COMPATIBLE_CHANNEL_AT_W4_SEC = 100010,
  L2CAP_SECURITY_NEG_AT_W4_SEC = 100011,
  L2CAP_TIMEOUT_AT_CONNECT_RSP = 100012,
  L2CAP_CONN_OTHER_ERROR_AT_CONNECT_RSP = 100013,
  SDP_SUCCESS = 100100,
  SDP_FAILURE = 100101,
  SDP_SENDING_DELAYED_UUID = 100102,
  SDP_NOT_SENDING_DELAYED_UUID = 100103,
  SDP_SENT_UUID = 100104,
  SDP_UUIDS_EQUAL_SKIP = 100105,
  SDP_ADD_UUID_WITH_INTENT = 100106,
  SDP_ADD_UUID_WITH_NO_INTENT = 100107,
  SDP_DROP_UUID = 100108,
  SDP_FETCH_UUID_SKIP_ALREADY_CACHED = 100109,
  SDP_FETCH_UUID_SKIP_ALREADY_BONDED = 100110,
  SDP_INVOKE_SDP_CYCLE = 100111,
  SDP_FETCH_UUID_REQUEST = 100112,
  RFCOMM_CONNECTION_SUCCESS_IND = 101000,
  RFCOMM_CONNECTION_SUCCESS_CNF = 101001,
  RFCOMM_PORT_START_CNF_FAILED = 101002,
  RFCOMM_PORT_START_CLOSE = 101003,
  RFCOMM_PORT_START_FAILED = 101004,
  RFCOMM_PORT_NEG_FAILED = 101005,
  RFCOMM_PORT_CLOSED = 101006,
  RFCOMM_PORT_PEER_CONNECTION_FAILED = 101007,
  RFCOMM_PORT_PEER_TIMEOUT = 101008,
  HFP_COLLISON_AT_AG_OPEN = 101101,
  HFP_COLLISON_AT_CONNECTING = 101102,
  HFP_SELF_INITIATED_AG_FAILED = 101103,
  HFP_SLC_SETUP_FAILED = 101104,
  A2DP_CONNECTION_SUCCESS = 102000,
  A2DP_CONNECTION_ACL_DISCONNECTED = 102001,
  A2DP_CONNECTION_REJECT_EVT = 102002,
  A2DP_CONNECTION_FAILURE = 102003,
  A2DP_CONNECTION_UNKNOWN_EVENT = 102004,
  A2DP_ALREADY_CONNECTING = 102005,
  A2DP_OFFLOAD_START_REQ_FAILURE = 102006,
  A2DP_CONNECTION_CLOSE = 102007,
  A2DP_CONNECTION_DISCONNECTED = 102008,
  A2DP_CONNECTION_TIMEOUT = 102009,
  HID_PLUG_FAILURE = 103001,
  HIDD_REGISTER_DESCRIPTOR_MALFORMED = 103002,
  HIDD_ERR_NOT_REGISTERED_AT_INITIATE = 103003,
  HIDD_ERR_NO_RESOURCES = 103004,
  HIDD_ERR_NO_CONNECTION_AT_SEND_DATA = 103005,
  HIDD_ERR_NO_CONNECTION_AT_DISCONNECT = 103006,
  HIDD_ERR_INVALID_PARAM = 103007,
  HIDD_ERR_CONGESTED_AT_DATA_WRITE = 103008,
  HIDD_ERR_CONGESTED_AT_FLAG_CHECK = 103009,
  HIDD_ERR_CONN_IN_PROCESS = 103010,
  HIDD_ERR_ALREADY_CONN = 103011,
  HIDD_ERR_DISCONNECTING = 103012,
  HIDD_ERR_L2CAP_NOT_STARTED_INCOMING = 103013,
  HIDD_ERR_L2CAP_FAILED_INITIATE = 103014,
  HIDD_ERR_L2CAP_FAILED_CONTROL = 103015,
  HIDD_ERR_L2CAP_FAILED_INTERRUPT = 103016,
  HIDD_ERR_HOST_CALLBACK_NULL = 103017,
  HIDD_ERR_INVALID_PARAM_SEND_REPORT = 103018,
  HIDD_ERR_DEVICE_NOT_IN_USE_AT_CONNECT = 103019,
  HIDD_ERR_DEVICE_NOT_IN_USE_AT_DISCONNECT = 103020,
  HIDD_ERR_NOT_REGISTERED_AT_CONNECT = 103021,
  HIDD_ERR_NOT_REGISTERED_AT_DISCONNECT = 103022,
  HIDD_ERR_NOT_REGISTERED_AT_GET_DEVICE = 103023,
  HIDD_ERR_NOT_REGISTERED_AT_DEREGISTER = 103024,
  HIDD_ERR_NOT_REGISTERED_DUE_TO_DESCRIPTOR_LENGTH = 103025,
  HIDD_ERR_NOT_REGISTERED_DUE_TO_BUFFER_ALLOCATION = 103026,
  HIDD_ERR_NOT_REGISTERED_AT_SDP = 103027,
  HIDD_ERR_ALREADY_REGISTERED = 103028,
  HIDH_ERR_ALREADY_REGISTERED = 103101,
  HIDH_ERR_NO_RESOURCES_SDP = 103102,
  HIDH_ERR_NO_RESOURCES_ADD_DEVICE = 103103,
  HIDH_ERR_NO_CONNECTION_AT_SEND_DATA = 103104,
  HIDH_ERR_NO_CONNECTION_AT_HOST_WRITE_DEV = 103105,
  HIDH_ERR_NO_CONNECTION_AT_HOST_CLOSE_DEV = 103106,
  HIDH_ERR_INVALID_PARAM_AT_SEND_DATA = 103107,
  HIDH_ERR_INVALID_PARAM_AT_HOST_REGISTER = 103108,
  HIDH_ERR_INVALID_PARAM_AT_HOST_REMOVE_DEV = 103109,
  HIDH_ERR_INVALID_PARAM_AT_HOST_OPEN_DEV = 103110,
  HIDH_ERR_INVALID_PARAM_AT_HOST_CLOSE_DEV = 103111,
  HIDH_ERR_INVALID_PARAM_AT_HOST_WRITE_DEV = 103112,
  HIDH_ERR_CONGESTED_AT_SEND_DATA = 103113,
  HIDH_ERR_CONGESTED_AT_FLAG_CHECK = 103114,
  HIDH_ERR_CONN_IN_PROCESS = 103115,
  HIDH_ERR_ALREADY_CONN = 103116,
  HIDH_ERR_L2CAP_FAILED_AT_INITIATE = 103117,
  HIDH_ERR_L2CAP_FAILED_AT_REGISTER_CONTROL = 103118,
  HIDH_ERR_L2CAP_FAILED_AT_REGISTER_INTERRUPT = 103119,
  HIDH_ERR_AUTH_FAILED = 103120,
  HIDH_ERR_SDP_BUSY = 103121,
  HIDH_COUNT_MAX_ADDED_DEVICE_LIMIT_REACHED = 103122,
  HIDH_COUNT_VIRTUAL_UNPLUG_REQUESTED_BY_REMOTE_DEVICE = 103123,
  HIDH_COUNT_CONNECT_REQ_WHEN_MAX_DEVICE_LIMIT_REACHED = 103124,
  HIDH_COUNT_WRONG_REPORT_TYPE = 103125,
  HIDH_COUNT_INCOMING_CONNECTION_REJECTED = 103126,
  HIDH_COUNT_CONNECTION_POLICY_DISABLED = 103127,
  HIDH_COUNT_SUPPORT_BOTH_HID_AND_HOGP = 103128,
  HIDH_COUNT_SUPPORT_ONLY_HID_OR_HOGP = 103129,
  LE_SCAN_COUNT_TOTAL_ENABLE = 120000,
  LE_SCAN_COUNT_TOTAL_DISABLE = 120001,
  LE_SCAN_COUNT_FILTERED_ENABLE = 120002,
  LE_SCAN_COUNT_FILTERED_DISABLE = 120003,
  LE_SCAN_COUNT_UNFILTERED_ENABLE = 120004,
  LE_SCAN_COUNT_UNFILTERED_DISABLE = 120005,
  LE_SCAN_COUNT_BATCH_ENABLE = 120006,
  LE_SCAN_COUNT_BATCH_DISABLE = 120007,
  LE_SCAN_COUNT_AUTO_BATCH_ENABLE = 120008,
  LE_SCAN_COUNT_AUTO_BATCH_DISABLE = 120009,
  LE_SCAN_DURATION_COUNT_REGULAR_10S = 120100,
  LE_SCAN_DURATION_COUNT_REGULAR_1M = 120101,
  LE_SCAN_DURATION_COUNT_REGULAR_10M = 120102,
  LE_SCAN_DURATION_COUNT_REGULAR_1H = 120103,
  LE_SCAN_DURATION_COUNT_REGULAR_1HP = 120104,
  LE_SCAN_DURATION_COUNT_BATCH_10S = 120105,
  LE_SCAN_DURATION_COUNT_BATCH_1M = 120106,
  LE_SCAN_DURATION_COUNT_BATCH_10M = 120107,
  LE_SCAN_DURATION_COUNT_BATCH_1H = 120108,
  LE_SCAN_DURATION_COUNT_BATCH_1HP = 120109,
  LE_SCAN_RADIO_DURATION_ALL = 120200,
  LE_SCAN_RADIO_DURATION_REGULAR = 120201,
  LE_SCAN_RADIO_DURATION_BATCH = 120202,
  LE_SCAN_RADIO_DURATION_REGULAR_SCREEN_ON = 120203,
  LE_SCAN_RADIO_DURATION_REGULAR_SCREEN_OFF = 120204,
  LE_SCAN_RADIO_DURATION_BATCH_SCREEN_ON = 120205,
  LE_SCAN_RADIO_DURATION_BATCH_SCREEN_OFF = 120206,
  LE_SCAN_RADIO_SCAN_MODE_OPPORTUNISTIC_COUNT = 120250,
  LE_SCAN_RADIO_SCAN_MODE_LOW_POWER_COUNT = 120251,
  LE_SCAN_RADIO_SCAN_MODE_BALANCED_COUNT = 120252,
  LE_SCAN_RADIO_SCAN_MODE_LOW_LATENCY_COUNT = 120253,
  LE_SCAN_RADIO_SCAN_MODE_AMBIENT_DISCOVERY_COUNT = 120254,
  LE_SCAN_RADIO_SCAN_MODE_SCREEN_OFF_COUNT = 120255,
  LE_SCAN_RADIO_SCAN_MODE_SCREEN_OFF_BALANCED_COUNT = 120256,
  LE_SCAN_RADIO_SCAN_MODE_OPPORTUNISTIC_COUNT_SCREEN_OFF = 120257,
  LE_SCAN_RADIO_SCAN_MODE_LOW_POWER_COUNT_SCREEN_OFF = 120258,
  LE_SCAN_RADIO_SCAN_MODE_BALANCED_COUNT_SCREEN_OFF = 120259,
  LE_SCAN_RADIO_SCAN_MODE_LOW_LATENCY_COUNT_SCREEN_OFF = 120260,
  LE_SCAN_RADIO_SCAN_MODE_AMBIENT_DISCOVERY_COUNT_SCREEN_OFF = 120261,
  LE_SCAN_RADIO_SCAN_MODE_SCREEN_OFF_COUNT_SCREEN_OFF = 120262,
  LE_SCAN_RADIO_SCAN_MODE_SCREEN_OFF_BALANCED_COUNT_SCREEN_OFF = 120263,
  LE_SCAN_RESULTS_COUNT_ALL = 120300,
  LE_SCAN_RESULTS_COUNT_REGULAR = 120301,
  LE_SCAN_RESULTS_COUNT_BATCH = 120302,
  LE_SCAN_RESULTS_COUNT_REGULAR_SCREEN_ON = 120303,
  LE_SCAN_RESULTS_COUNT_REGULAR_SCREEN_OFF = 120304,
  LE_SCAN_RESULTS_COUNT_BATCH_SCREEN_ON = 120305,
  LE_SCAN_RESULTS_COUNT_BATCH_SCREEN_OFF = 120306,
  LE_SCAN_RESULTS_COUNT_BATCH_BUNDLE = 120307,
  LE_SCAN_RESULTS_COUNT_BATCH_BUNDLE_SCREEN_ON = 120308,
  LE_SCAN_RESULTS_COUNT_BATCH_BUNDLE_SCREEN_OFF = 120309,
  LE_SCAN_ABUSE_COUNT_SCAN_TIMEOUT = 120400,
  LE_SCAN_ABUSE_COUNT_HW_FILTER_NOT_AVAILABLE = 120401,
  LE_SCAN_ABUSE_COUNT_TRACKING_HW_FILTER_NOT_AVAILABLE = 120402,
  LE_ADV_COUNT_ENABLE = 120500,
  LE_ADV_COUNT_DISABLE = 120501,
  LE_ADV_COUNT_CONNECTABLE_ENABLE = 120502,
  LE_ADV_COUNT_CONNECTABLE_DISABLE = 120503,
  LE_ADV_COUNT_PERIODIC_ENABLE = 120504,
  LE_ADV_COUNT_PERIODIC_DISABLE = 120505,
  LE_ADV_INSTANCE_COUNT_5 = 120600,
  LE_ADV_INSTANCE_COUNT_10 = 120601,
  LE_ADV_INSTANCE_COUNT_15 = 120602,
  LE_ADV_INSTANCE_COUNT_15P = 120603,
  LE_ADV_DURATION_COUNT_TOTAL_1M = 120700,
  LE_ADV_DURATION_COUNT_TOTAL_30M = 120701,
  LE_ADV_DURATION_COUNT_TOTAL_1H = 120702,
  LE_ADV_DURATION_COUNT_TOTAL_3H = 120703,
  LE_ADV_DURATION_COUNT_TOTAL_3HP = 120704,
  LE_ADV_DURATION_COUNT_CONNECTABLE_1M = 120705,
  LE_ADV_DURATION_COUNT_CONNECTABLE_30M = 120706,
  LE_ADV_DURATION_COUNT_CONNECTABLE_1H = 120707,
  LE_ADV_DURATION_COUNT_CONNECTABLE_3H = 120708,
  LE_ADV_DURATION_COUNT_CONNECTABLE_3HP = 120709,
  LE_ADV_DURATION_COUNT_PERIODIC_1M = 120710,
  LE_ADV_DURATION_COUNT_PERIODIC_30M = 120711,
  LE_ADV_DURATION_COUNT_PERIODIC_1H = 120712,
  LE_ADV_DURATION_COUNT_PERIODIC_3H = 120713,
  LE_ADV_DURATION_COUNT_PERIODIC_3HP = 120714,
  LE_ADV_ERROR_ON_START_COUNT = 120800,
  GATT_CLIENT_CONNECT_IS_DIRECT = 120900,
  GATT_CLIENT_CONNECT_IS_AUTOCONNECT = 120901,
  GATT_CLIENT_CONNECT_IS_DIRECT_IN_FOREGROUND = 120902,
  GATT_CLIENT_CONNECT_IS_DIRECT_NOT_IN_FOREGROUND = 120903,
  GATT_CLIENT_CONNECT_IS_AUTOCONNECT_IN_FOREGROUND = 120904,
  GATT_CLIENT_CONNECT_IS_AUTOCONNECT_NOT_IN_FOREGROUND = 120905,
  GATT_SERVER_CONNECT_IS_DIRECT_IN_FOREGROUND = 120906,
  GATT_SERVER_CONNECT_IS_DIRECT_NOT_IN_FOREGROUND = 120907,
  GATT_SERVER_CONNECT_IS_AUTOCONNECT_IN_FOREGROUND = 120908,
  GATT_SERVER_CONNECT_IS_AUTOCONNECT_NOT_IN_FOREGROUND = 120909,
  SCREEN_ON_EVENT = 121000,
  SCREEN_OFF_EVENT = 121001,
  LE_AUDIO_ALLOWLIST_DEVICE_HEALTH_STATUS_GOOD = 121100,
  LE_AUDIO_ALLOWLIST_DEVICE_HEALTH_STATUS_BAD = 121101,
  LE_AUDIO_ALLOWLIST_DEVICE_HEALTH_STATUS_BAD_INVALID_DB = 121102,
  LE_AUDIO_ALLOWLIST_DEVICE_HEALTH_STATUS_BAD_INVALID_CSIS = 121103,
  LE_AUDIO_NONALLOWLIST_DEVICE_HEALTH_STATUS_GOOD = 121104,
  LE_AUDIO_NONALLOWLIST_DEVICE_HEALTH_STATUS_BAD = 121105,
  LE_AUDIO_NONALLOWLIST_DEVICE_HEALTH_STATUS_BAD_INVALID_DB = 121106,
  LE_AUDIO_NONALLOWLIST_DEVICE_HEALTH_STATUS_BAD_INVALID_CSIS = 121107,
  LE_AUDIO_ALLOWLIST_GROUP_HEALTH_STATUS_GOOD = 121108,
  LE_AUDIO_ALLOWLIST_GROUP_HEALTH_STATUS_TRENDING_BAD = 121109,
  LE_AUDIO_ALLOWLIST_GROUP_HEALTH_STATUS_BAD = 121110,
  LE_AUDIO_ALLOWLIST_GROUP_HEALTH_STATUS_BAD_ONCE_CIS_FAILED = 121111,
  LE_AUDIO_ALLOWLIST_GROUP_HEALTH_STATUS_BAD_ONCE_SIGNALING_FAILED = 121112,
  LE_AUDIO_NONALLOWLIST_GROUP_HEALTH_STATUS_GOOD = 121113,
  LE_AUDIO_NONALLOWLIST_GROUP_HEALTH_STATUS_TRENDING_BAD = 121114,
  LE_AUDIO_NONALLOWLIST_GROUP_HEALTH_STATUS_BAD = 121115,
  LE_AUDIO_NONALLOWLIST_GROUP_HEALTH_STATUS_BAD_ONCE_CIS_FAILED = 121116,
  LE_AUDIO_NONALLOWLIST_GROUP_HEALTH_STATUS_BAD_ONCE_SIGNALING_FAILED = 121117,
};

bool CodePathCounterKeyEnum_IsValid(int value);
extern const uint32_t CodePathCounterKeyEnum_internal_data_[];
constexpr CodePathCounterKeyEnum CodePathCounterKeyEnum_MIN = static_cast<CodePathCounterKeyEnum>(0);
constexpr CodePathCounterKeyEnum CodePathCounterKeyEnum_MAX = static_cast<CodePathCounterKeyEnum>(121117);
constexpr int CodePathCounterKeyEnum_ARRAYSIZE = 121117 + 1;
const std::string& CodePathCounterKeyEnum_Name(CodePathCounterKeyEnum value);
template <typename T>
const std::string& CodePathCounterKeyEnum_Name(T value) {
  static_assert(std::is_same<T, CodePathCounterKeyEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to CodePathCounterKeyEnum_Name().");
  return CodePathCounterKeyEnum_Name(static_cast<CodePathCounterKeyEnum>(value));
}
const std::string& CodePathCounterKeyEnum_Name(CodePathCounterKeyEnum value);
bool CodePathCounterKeyEnum_Parse(absl::string_view name, CodePathCounterKeyEnum* value);
enum AddressTypeEnum : int {
  ADDRESS_TYPE_PUBLIC = 0,
  ADDRESS_TYPE_RANDOM = 1,
  ADDRESS_TYPE_UNKNOWN = 65535,
};

bool AddressTypeEnum_IsValid(int value);
extern const uint32_t AddressTypeEnum_internal_data_[];
constexpr AddressTypeEnum AddressTypeEnum_MIN = static_cast<AddressTypeEnum>(0);
constexpr AddressTypeEnum AddressTypeEnum_MAX = static_cast<AddressTypeEnum>(65535);
constexpr int AddressTypeEnum_ARRAYSIZE = 65535 + 1;
const std::string& AddressTypeEnum_Name(AddressTypeEnum value);
template <typename T>
const std::string& AddressTypeEnum_Name(T value) {
  static_assert(std::is_same<T, AddressTypeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AddressTypeEnum_Name().");
  return AddressTypeEnum_Name(static_cast<AddressTypeEnum>(value));
}
const std::string& AddressTypeEnum_Name(AddressTypeEnum value);
bool AddressTypeEnum_Parse(absl::string_view name, AddressTypeEnum* value);
enum MajorClassEnum : int {
  MAJOR_CLASS_UNCATEGORIZED = 7936,
  MAJOR_CLASS_MISC = 0,
  MAJOR_CLASS_COMPUTER = 256,
  MAJOR_CLASS_PHONE = 512,
  MAJOR_CLASS_NETWORKING = 768,
  MAJOR_CLASS_AUDIO_VIDEO = 1024,
  MAJOR_CLASS_PERIPHERAL = 1280,
  MAJOR_CLASS_IMAGING = 1536,
  MAJOR_CLASS_WEARABLE = 1792,
  MAJOR_CLASS_TOY = 2048,
  MAJOR_CLASS_HEALTH = 2304,
};

bool MajorClassEnum_IsValid(int value);
extern const uint32_t MajorClassEnum_internal_data_[];
constexpr MajorClassEnum MajorClassEnum_MIN = static_cast<MajorClassEnum>(0);
constexpr MajorClassEnum MajorClassEnum_MAX = static_cast<MajorClassEnum>(7936);
constexpr int MajorClassEnum_ARRAYSIZE = 7936 + 1;
const std::string& MajorClassEnum_Name(MajorClassEnum value);
template <typename T>
const std::string& MajorClassEnum_Name(T value) {
  static_assert(std::is_same<T, MajorClassEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MajorClassEnum_Name().");
  return MajorClassEnum_Name(static_cast<MajorClassEnum>(value));
}
const std::string& MajorClassEnum_Name(MajorClassEnum value);
bool MajorClassEnum_Parse(absl::string_view name, MajorClassEnum* value);
enum ProfileConnectionResult : int {
  RESULT_UNKNOWN = 0,
  RESULT_SUCCESS = 1,
  RESULT_FAILURE = 2,
};

bool ProfileConnectionResult_IsValid(int value);
extern const uint32_t ProfileConnectionResult_internal_data_[];
constexpr ProfileConnectionResult ProfileConnectionResult_MIN = static_cast<ProfileConnectionResult>(0);
constexpr ProfileConnectionResult ProfileConnectionResult_MAX = static_cast<ProfileConnectionResult>(2);
constexpr int ProfileConnectionResult_ARRAYSIZE = 2 + 1;
const std::string& ProfileConnectionResult_Name(ProfileConnectionResult value);
template <typename T>
const std::string& ProfileConnectionResult_Name(T value) {
  static_assert(std::is_same<T, ProfileConnectionResult>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ProfileConnectionResult_Name().");
  return ProfileConnectionResult_Name(static_cast<ProfileConnectionResult>(value));
}
const std::string& ProfileConnectionResult_Name(ProfileConnectionResult value);
bool ProfileConnectionResult_Parse(absl::string_view name, ProfileConnectionResult* value);
enum ProfileConnectionReason : int {
  REASON_UNKNOWN = 0,
  REASON_SUCCESS = 1,
  REASON_UNEXPECTED_STATE = 2,
  REASON_NATIVE_LAYER_REJECTED = 3,
  REASON_INCOMING_CONN_REJECTED = 4,
};

bool ProfileConnectionReason_IsValid(int value);
extern const uint32_t ProfileConnectionReason_internal_data_[];
constexpr ProfileConnectionReason ProfileConnectionReason_MIN = static_cast<ProfileConnectionReason>(0);
constexpr ProfileConnectionReason ProfileConnectionReason_MAX = static_cast<ProfileConnectionReason>(4);
constexpr int ProfileConnectionReason_ARRAYSIZE = 4 + 1;
const std::string& ProfileConnectionReason_Name(ProfileConnectionReason value);
template <typename T>
const std::string& ProfileConnectionReason_Name(T value) {
  static_assert(std::is_same<T, ProfileConnectionReason>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ProfileConnectionReason_Name().");
  return ProfileConnectionReason_Name(static_cast<ProfileConnectionReason>(value));
}
const std::string& ProfileConnectionReason_Name(ProfileConnectionReason value);
bool ProfileConnectionReason_Parse(absl::string_view name, ProfileConnectionReason* value);
enum LeConnectionResult : int {
  LE_CONNECTION_RESULT_UNKNOWN = 0,
  LE_CONNECTION_RESULT_SUCCESS = 1,
  LE_CONNECTION_RESULT_FAILURE = 2,
};

bool LeConnectionResult_IsValid(int value);
extern const uint32_t LeConnectionResult_internal_data_[];
constexpr LeConnectionResult LeConnectionResult_MIN = static_cast<LeConnectionResult>(0);
constexpr LeConnectionResult LeConnectionResult_MAX = static_cast<LeConnectionResult>(2);
constexpr int LeConnectionResult_ARRAYSIZE = 2 + 1;
const std::string& LeConnectionResult_Name(LeConnectionResult value);
template <typename T>
const std::string& LeConnectionResult_Name(T value) {
  static_assert(std::is_same<T, LeConnectionResult>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeConnectionResult_Name().");
  return LeConnectionResult_Name(static_cast<LeConnectionResult>(value));
}
const std::string& LeConnectionResult_Name(LeConnectionResult value);
bool LeConnectionResult_Parse(absl::string_view name, LeConnectionResult* value);
enum ContentProfileFileName : int {
  BLUETOOTH_FILE_NAME_UNKNOWN = 0,
  BLUETOOTH_MAP_ACCOUNT_LOADER = 1,
  BLUETOOTH_MAP_APP_OBSERVER = 2,
  BLUETOOTH_MAP_APP_PARAMS = 3,
  BLUETOOTH_MAP_BMESSAGE = 4,
  BLUETOOTH_MAP_BMESSAGE_EMAIL = 5,
  BLUETOOTH_MAP_BMESSAGE_MIME = 6,
  BLUETOOTH_MAP_CONTENT = 7,
  BLUETOOTH_MAP_CONTENT_OBSERVER = 8,
  BLUETOOTH_MAP_CONVO_CONTACT_ELEMENT = 9,
  BLUETOOTH_MAP_CONVO_LISTING = 10,
  BLUETOOTH_MAP_CONVO_LISTING_ELEMENT = 11,
  BLUETOOTH_MAP_FOLDER_ELEMENT = 12,
  BLUETOOTH_MAP_MAS_INSTANCE = 13,
  BLUETOOTH_MAP_MESSAGE_LISTING = 14,
  BLUETOOTH_MAP_OBEX_SERVER = 15,
  BLUETOOTH_MAP_SERVICE = 16,
  BLUETOOTH_MAP_SMS_PDU = 17,
  BLUETOOTH_MAP_UTILS = 18,
  BLUETOOTH_MNS_OBEX_CLIENT = 19,
  BLUETOOTH_SMS_MMS_CONTACTS = 20,
  BLUETOOTH_MMS_FILE_PROVIDER = 21,
  BLUETOOTH_OPP_MANAGER = 10001,
  BLUETOOTH_OPP_TRANSFER_HISTORY = 10002,
  BLUETOOTH_OPP_OBEX_CLIENT_SESSION = 10003,
  BLUETOOTH_OPP_UTILITY = 10004,
  BLUETOOTH_OPP_LAUNCHER_ACTIVITY = 10005,
  BLUETOOTH_OPP_RECEIVER = 10006,
  BLUETOOTH_OPP_TRANSFER = 10007,
  BLUETOOTH_OPP_SEND_FILE_INFO = 10008,
  BLUETOOTH_OPP_INCOMING_FILE_CONFIRM_ACTIVITY = 10009,
  BLUETOOTH_OPP_OBEX_SERVER_SESSION = 10010,
  BLUETOOTH_OPP_RECEIVE_FILE_INFO = 10011,
  BLUETOOTH_OPP_TRANSFER_ACTIVITY = 10012,
  BLUETOOTH_OPP_PROVIDER = 10013,
  BLUETOOTH_OPP_SERVICE = 10014,
  BLUETOOTH_OPP_CONSTANTS = 10015,
  BLUETOOTH_PBAP_ACTIVITY = 20001,
  BLUETOOTH_PBAP_AUTHENTICATOR = 20002,
  BLUETOOTH_PBAP_CALL_LOG_COMPOSER = 20003,
  BLUETOOTH_PBAP_CONFIG = 20004,
  BLUETOOTH_PBAP_OBEX_SERVER = 20005,
  BLUETOOTH_PBAP_SERVICE = 20006,
  BLUETOOTH_PBAP_SIM_VCARD_MANAGER = 20007,
  BLUETOOTH_PBAP_UTILS = 20008,
  BLUETOOTH_PBAP_VCARD_MANAGER = 20009,
  BLUETOOTH_PBAP_HANDLER_FOR_STRING_BUFFER = 20010,
  BLUETOOTH_PBAP_STATE_MACHINE = 20011,
};

bool ContentProfileFileName_IsValid(int value);
extern const uint32_t ContentProfileFileName_internal_data_[];
constexpr ContentProfileFileName ContentProfileFileName_MIN = static_cast<ContentProfileFileName>(0);
constexpr ContentProfileFileName ContentProfileFileName_MAX = static_cast<ContentProfileFileName>(20011);
constexpr int ContentProfileFileName_ARRAYSIZE = 20011 + 1;
const std::string& ContentProfileFileName_Name(ContentProfileFileName value);
template <typename T>
const std::string& ContentProfileFileName_Name(T value) {
  static_assert(std::is_same<T, ContentProfileFileName>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ContentProfileFileName_Name().");
  return ContentProfileFileName_Name(static_cast<ContentProfileFileName>(value));
}
const std::string& ContentProfileFileName_Name(ContentProfileFileName value);
bool ContentProfileFileName_Parse(absl::string_view name, ContentProfileFileName* value);
enum EventType : int {
  EVENT_TYPE_UNKNOWN = 0,
  ACL_CONNECTION_RESPONDER = 1,
  ACL_CONNECTION_INITIATOR = 2,
  PROFILE_CONNECTION = 3,
  AUTHENTICATION_REQUEST = 4,
  IO_CAPABILITY_REQUEST = 5,
  USER_CONF_REQUEST = 6,
  USER_CONF_POSITIVE_REPLY = 7,
  USER_CONF_NEGATIVE_REPLY = 8,
  AUTHENTICATION_COMPLETE = 9,
  SERVICE_DISCOVERY = 10,
  REMOTE_NAME_REQUEST = 11,
  ACL_DISCONNECTION_INITIATOR = 12,
  ACL_DISCONNECTION_RESPONDER = 13,
  AUTHENTICATION_COMPLETE_FAIL = 14,
  BONDING = 15,
  INITIATOR_CONNECTION = 16,
  BOND = 17,
  PROFILE_CONNECTION_A2DP = 18,
  PROFILE_CONNECTION_A2DP_SINK = 19,
  PROFILE_CONNECTION_HEADSET = 20,
  PROFILE_CONNECTION_HEADSET_CLIENT = 21,
  PROFILE_CONNECTION_MAP_CLIENT = 22,
  PROFILE_CONNECTION_HID_HOST = 23,
  PROFILE_CONNECTION_PAN = 24,
  PROFILE_CONNECTION_PBAP_CLIENT = 25,
  PROFILE_CONNECTION_HEARING_AID = 26,
  PROFILE_CONNECTION_HAP_CLIENT = 27,
  PROFILE_CONNECTION_VOLUME_CONTROL = 28,
  PROFILE_CONNECTION_CSIP_SET_COORDINATOR = 29,
  PROFILE_CONNECTION_LE_AUDIO = 30,
  PROFILE_CONNECTION_LE_AUDIO_BROADCAST_ASSISTANT = 31,
  PROFILE_CONNECTION_BATTERY = 32,
  TRANSPORT = 33,
  BOND_RETRY = 34,
  SMP_PAIRING_OUTGOING = 35,
  SMP_PAIRING_INCOMING = 36,
  LE_ACL_CONNECTION_INITIATOR = 37,
  LE_ACL_CONNECTION_RESPONDER = 38,
  LE_ACL_DISCONNECTION_INITIATOR = 39,
  LE_ACL_DISCONNECTION_RESPONDER = 40,
  GATT_CONNECT_JAVA = 41,
  GATT_CONNECT_NATIVE = 42,
  LE_DEVICE_IN_ACCEPT_LIST = 43,
  GATT_DISCONNECT_JAVA = 44,
  GATT_DISCONNECT_NATIVE = 45,
  TRANSPORT_MATCH = 46,
  HFP_SESSION = 47,
  HFP_AG_VERSION = 48,
  HFP_HF_VERSION = 49,
  HFP_HF_FEATURES = 50,
  SCO_SESSION = 51,
  SCO_CODEC = 52,
  TRANSITION = 53,
  LE_CONNECTION_REJECTED = 54,
  AVDTP_L2CAP_CONNECTION_REQUEST_SENT = 500,
  AVDTP_L2CAP_CONNECTION_REQUEST_RECEIVED = 501,
  AVDTP_L2CAP_CONNECTION_RESPONSE_SENT = 502,
  AVDTP_L2CAP_CONNECTION_RESPONSE_RECEIVED = 503,
  AVDTP_L2CAP_DISCONNECTION_REQUEST_SENT = 504,
  AVDTP_L2CAP_DISCONNECTION_REQUEST_RECEIVED = 505,
  AVDTP_L2CAP_DISCONNECTION_RESPONSE_SENT = 506,
  AVDTP_L2CAP_DISCONNECTION_RESPONSE_RECEIVED = 507,
  AVDTP_ON_L2CAP_ERROR = 510,
  AVDTP_DISC_FAIL_EVT = 560,
  AVDTP_GETCAP_FAIL_EVT = 561,
  AVDTP_OPEN_FAIL_EVT = 562,
  AVDTP_OPEN_REJECT_EVT = 563,
  AVDTP_SET_CONFIG_REJECT_EVT = 564,
  AVDTP_START_REJECT_EVT = 565,
  AVDTP_SUSPEND_REJECT_EVT = 566,
  AVDTP_SIGNALING_TIMEOUT = 567,
  AVDTP_ABORT_RESPONSE_SEND_EVT = 568,
  AVDTP_CLOSE_RESPONSE_SEND_EVT = 569,
  A2DP_BTIF_AV_STATE_CHANGE_EVT = 600,
  A2DP_PROFILE_STATE_CHANGE = 800,
  A2DP_PROFILE_ERROR_STATE_CHANGE = 801,
};

bool EventType_IsValid(int value);
extern const uint32_t EventType_internal_data_[];
constexpr EventType EventType_MIN = static_cast<EventType>(0);
constexpr EventType EventType_MAX = static_cast<EventType>(801);
constexpr int EventType_ARRAYSIZE = 801 + 1;
const std::string& EventType_Name(EventType value);
template <typename T>
const std::string& EventType_Name(T value) {
  static_assert(std::is_same<T, EventType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EventType_Name().");
  return EventType_Name(static_cast<EventType>(value));
}
const std::string& EventType_Name(EventType value);
bool EventType_Parse(absl::string_view name, EventType* value);
enum State : int {
  STATE_UNKNOWN = 0,
  START = 1,
  END = 2,
  SUCCESS = 3,
  FAIL = 4,
  ALREADY_CONNECTED = 5,
  TIMEOUT = 6,
  REMOTE_USER_TERMINATED_CONNECTION = 7,
  KEY_MISSING = 8,
  MEMORY_EXCEEDED = 9,
  BUSY_PAIRING = 10,
  REPEATED_ATTEMPTS = 11,
  PAIRING_NOT_ALLOWED = 12,
  RESOURCES_EXCEEDED = 13,
  AUTH_FAILURE = 14,
  LOCAL_DEVICE_TERMINATED_CONNECTION = 15,
  TRANSACTION_COLLISION = 16,
  PAGE_TIMEOUT = 17,
  CONNECTION_TIMEOUT = 18,
  CONNECTION_ACCEPT_TIMEOUT = 19,
  TRANSACTION_RESPONSE_TIMEOUT = 20,
  STATE_NONE = 21,
  STATE_BONDED = 22,
  CLASSIC = 23,
  LE = 24,
  HARDWARE_FAILURE = 25,
  MEMORY_CAPACITY_EXCEEDED = 26,
  CONNECTION_LIMIT_EXCEEDED = 27,
  SYNCHRONOUS_CONNECTION_LIMIT_EXCEEDED = 28,
  CONNECTION_REJECTED_SECURITY_REASONS = 29,
  CONNECTION_REJECTED_UNACCEPTABLE_BD_ADDR = 30,
  UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE = 31,
  INVALID_HCI_COMMAND_PARAMETERS = 32,
  UNSUPPORTED_REMOTE_OR_LMP_FEATURE = 33,
  SCO_OFFSET_REJECTED = 34,
  SCO_INTERVAL_REJECTED = 35,
  SCO_AIR_MODE_REJECTED = 36,
  INVALID_LMP_OR_LL_PARAMETERS = 37,
  UNSPECIFIED_ERROR = 38,
  UNSUPPORTED_LMP_OR_LL_PARAMETER = 39,
  ROLE_CHANGE_NOT_ALLOWED = 40,
  LINK_LAYER_COLLISION = 41,
  LMP_PDU_NOT_ALLOWED = 42,
  ENCRYPTION_MODE_NOT_ACCEPTABLE = 43,
  LINK_KEY_CANNOT_BE_CHANGED = 44,
  REQUESTED_QOS_NOT_SUPPORTED = 45,
  INSTANT_PASSED = 46,
  PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 47,
  DIFFERENT_TRANSACTION_COLLISION = 48,
  QOS_UNACCEPTABLE_PARAMETERS = 49,
  QOS_REJECTED = 50,
  CHANNEL_ASSESSMENT_NOT_SUPPORTED = 51,
  INSUFFICIENT_SECURITY = 52,
  PARAMETER_OUT_OF_MANDATORY_RANGE = 53,
  ROLE_SWITCH_PENDING = 54,
  RESERVED_SLOT_VIOLATION = 55,
  ROLE_SWITCH_FAILED = 56,
  EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 57,
  SECURE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 58,
  HOST_BUSY_PAIRING = 59,
  CONNECTION_REJECTED_NO_SUITABLE_CHANNEL_FOUND = 60,
  CONTROLLER_BUSY = 61,
  UNACCEPTABLE_CONNECTION_PARAMETERS = 62,
  ADVERTISING_TIMEOUT = 63,
  CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE = 64,
  CONNECTION_FAILED_ESTABLISHMENT = 65,
  COARSE_CLOCK_ADJUSTMENT_REJECTED = 66,
  TYPE0_SUBMAP_NOT_DEFINED = 67,
  UNKNOWN_ADVERTISING_IDENTIFIER = 68,
  LIMIT_REACHED = 69,
  OPERATION_CANCELLED_BY_HOST = 70,
  PACKET_TOO_LONG = 71,
  CONNECTION_TERMINATED_BY_LOCAL_HOST = 72,
  PASSKEY_ENTRY_FAIL = 73,
  OOB_FAIL = 74,
  CONFIRM_VALUE_ERROR = 75,
  ENC_KEY_SIZE = 76,
  INVALID_CMD = 77,
  INVALID_PARAMETERS = 78,
  DHKEY_CHK_FAIL = 79,
  NUMERIC_COMPARISON_FAIL = 80,
  BR_PAIRING_IN_PROGRESS = 81,
  CROSS_TRANSPORT_NOT_ALLOWED = 82,
  INTERNAL_ERROR = 83,
  UNKNOWN_IO_CAP = 84,
  ENCRYPTION_FAIL = 85,
  RESPONSE_TIMEOUT = 86,
  SIRK_DEVICE_INVALID = 87,
  USER_CANCELLATION = 88,
  DIRECT_CONNECT = 89,
  INDIRECT_CONNECT = 90,
  HFP_CONNECTED = 91,
  HFP_SLC_FAIL_CONNECTION = 92,
  HFP_RFCOMM_CHANNEL_FAIL = 93,
  HFP_RFCOMM_COLLISION_FAIL = 94,
  HFP_RFCOMM_AG_OPEN_FAIL = 95,
  HFP_CONNECT_FAIL = 96,
  SCO_TELECOM_INITIATED_START = 97,
  SCO_VIRTUAL_VOICE_INITIATED_START = 98,
  SCO_VOICE_RECOGNITION_INITIATED_START = 99,
  SCO_CONNECT_AUDIO_START = 100,
  SCO_LINK_CREATED = 101,
  SCO_AUDIO_CONNECTED = 102,
  SCO_LINK_REMOVED = 103,
  SCO_TELECOM_INITIATED_END = 104,
  SCO_VIRTUAL_VOICE_INITIATED_END = 105,
  SCO_VOICE_RECOGNITION_INITIATED_END = 106,
  SCO_DISCONNECT_AUDIO_END = 107,
  ILLEGAL_COMMAND = 108,
  NO_CONNECTION = 109,
  HW_FAILURE = 110,
  MEMORY_FULL = 111,
  MAX_NUMBER_OF_CONNECTIONS = 112,
  MAX_NUM_OF_SCOS = 113,
  CONNECTION_EXISTS = 114,
  COMMAND_DISALLOWED = 115,
  HOST_REJECT_RESOURCES = 116,
  HOST_REJECT_SECURITY = 117,
  ILLEGAL_PARAMETER_FMT = 118,
  PEER_USER = 119,
  REMOTE_LOW_RESOURCE = 120,
  REMOTE_POWER_OFF = 121,
  CONN_CAUSE_LOCAL_HOST = 122,
  HOST_REJECT_DEVICE = 123,
  UNSUPPORTED_REM_FEATURE = 124,
  UNSPECIFIED = 125,
  UNACCEPT_CONN_INTERVAL = 126,
  UNIT_KEY_USED = 127,
  DIFF_TRANSACTION_COLLISION = 128,
  LMP_ERR_TRANS_COLLISION = 129,
  CANCELLED_BY_LOCAL_HOST = 130,
  MAX_ERR = 131,
  UNDEFINED = 132,
  BOND_BONDED_TO_ACTION_KEY_MISSING = 133,
  ACTION_KEY_MISSING_TO_ENCRYPTION_CHANGE = 134,
  ACTION_KEY_MISSING_TO_BOND_NONE = 135,
  UNKNOWN_HCI_COMMAND = 136,
  REMOTE_DEVICE_TERMINATED_CONNECTION_LOW_RESOURCES = 137,
  REMOTE_DEVICE_TERMINATED_CONNECTION_POWER_OFF = 138,
  UNKNOWN_LMP_PDU = 139,
  VERSION_1_0 = 140,
  VERSION_1_1 = 141,
  VERSION_1_2 = 142,
  VERSION_1_3 = 143,
  VERSION_1_4 = 144,
  VERSION_1_5 = 145,
  VERSION_1_6 = 146,
  VERSION_1_7 = 147,
  VERSION_1_8 = 148,
  VERSION_1_9 = 149,
  VERSION_UNKNOWN = 150,
  START_LOCAL_INITIATED = 151,
  START_REMOTE_INITIATED = 152,
  HFP_CONNECT_REJECT_FAIL = 153,
  HFP_ACL_CONNECT_FAIL = 154,
  ATTEMPT_IN_PROGRESS = 155,
  CODEC_CVSD = 156,
  CODEC_MSBC = 157,
  CODEC_LC3 = 158,
  CODEC_UNKNOWN = 159,
  SCO_LINK_LOSS = 160,
  CODEC_APTX_SWB_SETTINGS_Q0_MASK = 161,
  CODEC_APTX_SWB_SETTINGS_Q1_MASK = 162,
  CODEC_APTX_SWB_SETTINGS_Q2_MASK = 163,
  CODEC_APTX_SWB_SETTINGS_Q3_MASK = 164,
  SCO_VOICE_RECOGNITION_HEADSET_START = 165,
  SCO_VOICE_RECOGNITION_HEADSET_END = 166,
  SCO_VOICE_RECOGNITION_HEADSET_TIMEOUT = 167,
  AUDIO_PORT_START_STREAM = 168,
  AUDIO_PORT_SUSPEND_STREAM = 169,
  AUDIO_PROVIDER_STREAM_STARTED = 170,
  SDP_DISCOVERY_FAILED = 171,
  RFCOMM_CONNECTION_FAILED = 172,
  L2CAP_CONN_STATUS_OK = 500,
  L2CAP_CONN_STATUS_PENDING = 501,
  L2CAP_CONN_STATUS_NO_PSM = 502,
  L2CAP_CONN_STATUS_SECURITY_BLOCK = 503,
  L2CAP_CONN_STATUS_NO_RESOURCES = 504,
  L2CAP_CONN_STATUS_TIMEOUT = 505,
  L2CAP_CONN_STATUS_OTHER_ERROR = 506,
  L2CAP_CONN_STATUS_ACL_CONNECTION_FAILED = 507,
  L2CAP_CONN_STATUS_CLIENT_SECURITY_CLEARANCE_FAILED = 508,
  L2CAP_CONN_STATUS_NO_LINK = 509,
  L2CAP_CONN_STATUS_INSUFFICIENT_AUTHENTICATION = 510,
  L2CAP_CONN_STATUS_INSUFFICIENT_AUTHORIZATION = 511,
  L2CAP_CONN_STATUS_INSUFFICIENT_ENCRYP_KEY_SIZE = 512,
  L2CAP_CONN_STATUS_INSUFFICIENT_ENCRYP = 513,
  L2CAP_CONN_STATUS_INVALID_SOURCE_CID = 514,
  L2CAP_CONN_STATUS_SOURCE_CID_ALREADY_ALLOCATED = 515,
  L2CAP_CONN_STATUS_UNACCEPTABLE_PARAMETERS = 516,
  L2CAP_CONN_STATUS_INVALID_PARAMETERS = 517,
  L2CAP_CONN_STATUS_UNKNOWN_ERROR = 518,
  A2DP_EVENT_STATUS_SUCCESS = 1000,
  A2DP_EVENT_STATUS_FAILURE = 1001,
  A2DP_STATE_DISCONNECTED = 1010,
  A2DP_STATE_CONNECTING = 1011,
  A2DP_STATE_CONNECTED = 1012,
  A2DP_STATE_DISCONNECTING = 1013,
  A2DP_STATE_PLAYING = 1014,
  A2DP_STATE_NOT_PLAYING = 1015,
  BTA_AV_STATUS_SUCCESS = 1020,
  BTA_AV_STATUS_FAIL = 1021,
  BTA_AV_STATUS_FAIL_SDP = 1022,
  BTA_AV_STATUS_FAIL_STREAM = 1023,
  BTA_AV_STATUS_FAIL_RESOURCES = 2014,
  BTA_AV_STATUS_FAIL_ROLE = 1025,
  BTA_AV_STATUS_FAIL_GET_CAP = 1026,
  AVDT_STATUS_ERR_CONNECT = 1060,
  AVDT_STATUS_ERR_TIMEOUT = 1061,
  AVDTP_STATUS_UNKNOWN_ERROR = 1062,
};

bool State_IsValid(int value);
extern const uint32_t State_internal_data_[];
constexpr State State_MIN = static_cast<State>(0);
constexpr State State_MAX = static_cast<State>(2014);
constexpr int State_ARRAYSIZE = 2014 + 1;
const std::string& State_Name(State value);
template <typename T>
const std::string& State_Name(T value) {
  static_assert(std::is_same<T, State>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to State_Name().");
  return State_Name(static_cast<State>(value));
}
const std::string& State_Name(State value);
bool State_Parse(absl::string_view name, State* value);
enum RemoteDeviceTypeMetadata : int {
  WATCH = 0,
  UNTETHERED_HEADSET = 1,
  STYLUS = 2,
  SPEAKER = 3,
  HEADSET = 4,
  CARKIT = 5,
  DEFAULT = 6,
  NOT_AVAILABLE = 7,
};

bool RemoteDeviceTypeMetadata_IsValid(int value);
extern const uint32_t RemoteDeviceTypeMetadata_internal_data_[];
constexpr RemoteDeviceTypeMetadata RemoteDeviceTypeMetadata_MIN = static_cast<RemoteDeviceTypeMetadata>(0);
constexpr RemoteDeviceTypeMetadata RemoteDeviceTypeMetadata_MAX = static_cast<RemoteDeviceTypeMetadata>(7);
constexpr int RemoteDeviceTypeMetadata_ARRAYSIZE = 7 + 1;
const std::string& RemoteDeviceTypeMetadata_Name(RemoteDeviceTypeMetadata value);
template <typename T>
const std::string& RemoteDeviceTypeMetadata_Name(T value) {
  static_assert(std::is_same<T, RemoteDeviceTypeMetadata>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RemoteDeviceTypeMetadata_Name().");
  return RemoteDeviceTypeMetadata_Name(static_cast<RemoteDeviceTypeMetadata>(value));
}
const std::string& RemoteDeviceTypeMetadata_Name(RemoteDeviceTypeMetadata value);
bool RemoteDeviceTypeMetadata_Parse(absl::string_view name, RemoteDeviceTypeMetadata* value);
enum BroadcastAudioQualityType : int {
  QUALITY_UNKNOWN = 0,
  QUALITY_STANDARD = 1,
  QUALITY_HIGH = 2,
};

bool BroadcastAudioQualityType_IsValid(int value);
extern const uint32_t BroadcastAudioQualityType_internal_data_[];
constexpr BroadcastAudioQualityType BroadcastAudioQualityType_MIN = static_cast<BroadcastAudioQualityType>(0);
constexpr BroadcastAudioQualityType BroadcastAudioQualityType_MAX = static_cast<BroadcastAudioQualityType>(2);
constexpr int BroadcastAudioQualityType_ARRAYSIZE = 2 + 1;
const std::string& BroadcastAudioQualityType_Name(BroadcastAudioQualityType value);
template <typename T>
const std::string& BroadcastAudioQualityType_Name(T value) {
  static_assert(std::is_same<T, BroadcastAudioQualityType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BroadcastAudioQualityType_Name().");
  return BroadcastAudioQualityType_Name(static_cast<BroadcastAudioQualityType>(value));
}
const std::string& BroadcastAudioQualityType_Name(BroadcastAudioQualityType value);
bool BroadcastAudioQualityType_Parse(absl::string_view name, BroadcastAudioQualityType* value);
enum BroadcastSessionSetupStatus : int {
  SETUP_STATUS_UNKNOWN = 0,
  SETUP_STATUS_REQUESTED = 1,
  SETUP_STATUS_CREATED = 2,
  SETUP_STATUS_STREAMING = 3,
  SETUP_STATUS_CREATE_FAILED = 4,
  SETUP_STATUS_STREAMING_FAILED = 5,
};

bool BroadcastSessionSetupStatus_IsValid(int value);
extern const uint32_t BroadcastSessionSetupStatus_internal_data_[];
constexpr BroadcastSessionSetupStatus BroadcastSessionSetupStatus_MIN = static_cast<BroadcastSessionSetupStatus>(0);
constexpr BroadcastSessionSetupStatus BroadcastSessionSetupStatus_MAX = static_cast<BroadcastSessionSetupStatus>(5);
constexpr int BroadcastSessionSetupStatus_ARRAYSIZE = 5 + 1;
const std::string& BroadcastSessionSetupStatus_Name(BroadcastSessionSetupStatus value);
template <typename T>
const std::string& BroadcastSessionSetupStatus_Name(T value) {
  static_assert(std::is_same<T, BroadcastSessionSetupStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BroadcastSessionSetupStatus_Name().");
  return BroadcastSessionSetupStatus_Name(static_cast<BroadcastSessionSetupStatus>(value));
}
const std::string& BroadcastSessionSetupStatus_Name(BroadcastSessionSetupStatus value);
bool BroadcastSessionSetupStatus_Parse(absl::string_view name, BroadcastSessionSetupStatus* value);
enum BroadcastSyncStatus : int {
  SYNC_STATUS_UNKNOWN = 0,
  SYNC_STATUS_SYNC_REQUESTED = 1,
  SYNC_STATUS_PA_SYNC_SUCCESS = 2,
  SYNC_STATUS_AUDIO_SYNC_SUCCESS = 3,
  SYNC_STATUS_PA_SYNC_FAILED = 4,
  SYNC_STATUS_PA_SYNC_NO_PAST = 5,
  SYNC_STATUS_BIG_DECRYPT_FAILED = 6,
  SYNC_STATUS_AUDIO_SYNC_FAILED = 7,
};

bool BroadcastSyncStatus_IsValid(int value);
extern const uint32_t BroadcastSyncStatus_internal_data_[];
constexpr BroadcastSyncStatus BroadcastSyncStatus_MIN = static_cast<BroadcastSyncStatus>(0);
constexpr BroadcastSyncStatus BroadcastSyncStatus_MAX = static_cast<BroadcastSyncStatus>(7);
constexpr int BroadcastSyncStatus_ARRAYSIZE = 7 + 1;
const std::string& BroadcastSyncStatus_Name(BroadcastSyncStatus value);
template <typename T>
const std::string& BroadcastSyncStatus_Name(T value) {
  static_assert(std::is_same<T, BroadcastSyncStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BroadcastSyncStatus_Name().");
  return BroadcastSyncStatus_Name(static_cast<BroadcastSyncStatus>(value));
}
const std::string& BroadcastSyncStatus_Name(BroadcastSyncStatus value);
bool BroadcastSyncStatus_Parse(absl::string_view name, BroadcastSyncStatus* value);
enum BtaStatus : int {
  BTA_STATUS_UNKNOWN = 0,
  BTA_STATUS_SUCCESS = 1,
  BTA_STATUS_FAILURE = 2,
  BTA_STATUS_BUSY = 3,
};

bool BtaStatus_IsValid(int value);
extern const uint32_t BtaStatus_internal_data_[];
constexpr BtaStatus BtaStatus_MIN = static_cast<BtaStatus>(0);
constexpr BtaStatus BtaStatus_MAX = static_cast<BtaStatus>(3);
constexpr int BtaStatus_ARRAYSIZE = 3 + 1;
const std::string& BtaStatus_Name(BtaStatus value);
template <typename T>
const std::string& BtaStatus_Name(T value) {
  static_assert(std::is_same<T, BtaStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BtaStatus_Name().");
  return BtaStatus_Name(static_cast<BtaStatus>(value));
}
const std::string& BtaStatus_Name(BtaStatus value);
bool BtaStatus_Parse(absl::string_view name, BtaStatus* value);
enum ChannelSoundingType : int {
  CS_UNSPECIFIED = 0,
  CS_BT_CORE60 = 1,
};

bool ChannelSoundingType_IsValid(int value);
extern const uint32_t ChannelSoundingType_internal_data_[];
constexpr ChannelSoundingType ChannelSoundingType_MIN = static_cast<ChannelSoundingType>(0);
constexpr ChannelSoundingType ChannelSoundingType_MAX = static_cast<ChannelSoundingType>(1);
constexpr int ChannelSoundingType_ARRAYSIZE = 1 + 1;
const std::string& ChannelSoundingType_Name(ChannelSoundingType value);
template <typename T>
const std::string& ChannelSoundingType_Name(T value) {
  static_assert(std::is_same<T, ChannelSoundingType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ChannelSoundingType_Name().");
  return ChannelSoundingType_Name(static_cast<ChannelSoundingType>(value));
}
const std::string& ChannelSoundingType_Name(ChannelSoundingType value);
bool ChannelSoundingType_Parse(absl::string_view name, ChannelSoundingType* value);
enum ChannelSoundingStopReason : int {
  REASON_UNSPECIFIED = 0,
  REASON_LOCAL_APP_REQUEST = 1,
  REASON_HAL_OPEN_FAILED = 2,
  REASON_CONFIG_ID_RUN_OUT = 3,
  REASON_LOCAL_CS_STACK_NOT_READY = 4,
  REASON_LE_DISCONNECT = 5,
  REASON_VENDOR_SPECIFIC_REPLY_FAILED = 6,
  REASON_B2B_CONFLICT = 7,
  REASON_REMOTE_TIMEOUT = 8,
  REASON_PROCEDURE_ENABLE_COMMAND_STATUS_ERROR = 9,
  REASON_READ_REMOTE_CAP_COMPLETE_FAILED = 10,
  REASON_SET_DEFAULT_SETTINGS_COMPLETE_FAILED = 11,
  REASON_SECURITY_ENABLE_COMPLETE_FAILED = 12,
  REASON_CREATE_CONFIG_COMPLETE_FAILED = 13,
  REASON_SECURITY_ENABLE_TIMEOUT = 14,
  REASON_SET_PROCEDURE_PARAMETERS_COMPLETE_FAILED = 15,
  REASON_PROCEDURE_ENABLE_COMPLETE_FAILED = 16,
  REASON_REMOTE_PROCEDURE_DATA_BROKEN = 17,
  REASON_READ_REMOTE_CAP_COMMAND_STATUS_ERROR = 18,
  REASON_SECURITY_ENABLE_COMMAND_STATUS_ERROR = 19,
  REASON_CREATE_CONFIG_COMMAND_STATUS_ERROR = 20,
  REASON_RAS_REMOTE_NOT_SUPPORT = 21,
  REASON_RAS_FATAL_ERROR = 22,
};

bool ChannelSoundingStopReason_IsValid(int value);
extern const uint32_t ChannelSoundingStopReason_internal_data_[];
constexpr ChannelSoundingStopReason ChannelSoundingStopReason_MIN = static_cast<ChannelSoundingStopReason>(0);
constexpr ChannelSoundingStopReason ChannelSoundingStopReason_MAX = static_cast<ChannelSoundingStopReason>(22);
constexpr int ChannelSoundingStopReason_ARRAYSIZE = 22 + 1;
const std::string& ChannelSoundingStopReason_Name(ChannelSoundingStopReason value);
template <typename T>
const std::string& ChannelSoundingStopReason_Name(T value) {
  static_assert(std::is_same<T, ChannelSoundingStopReason>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ChannelSoundingStopReason_Name().");
  return ChannelSoundingStopReason_Name(static_cast<ChannelSoundingStopReason>(value));
}
const std::string& ChannelSoundingStopReason_Name(ChannelSoundingStopReason value);
bool ChannelSoundingStopReason_Parse(absl::string_view name, ChannelSoundingStopReason* value);
enum ChannelSoundingSecurityLevel : int {
  LEVEL_UNSPECIFIED = 0,
  LEVEL_ONE = 1,
  LEVEL_TWO = 2,
  LEVEL_THREE = 3,
  LEVEL_FOUR = 4,
};

bool ChannelSoundingSecurityLevel_IsValid(int value);
extern const uint32_t ChannelSoundingSecurityLevel_internal_data_[];
constexpr ChannelSoundingSecurityLevel ChannelSoundingSecurityLevel_MIN = static_cast<ChannelSoundingSecurityLevel>(0);
constexpr ChannelSoundingSecurityLevel ChannelSoundingSecurityLevel_MAX = static_cast<ChannelSoundingSecurityLevel>(4);
constexpr int ChannelSoundingSecurityLevel_ARRAYSIZE = 4 + 1;
const std::string& ChannelSoundingSecurityLevel_Name(ChannelSoundingSecurityLevel value);
template <typename T>
const std::string& ChannelSoundingSecurityLevel_Name(T value) {
  static_assert(std::is_same<T, ChannelSoundingSecurityLevel>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ChannelSoundingSecurityLevel_Name().");
  return ChannelSoundingSecurityLevel_Name(static_cast<ChannelSoundingSecurityLevel>(value));
}
const std::string& ChannelSoundingSecurityLevel_Name(ChannelSoundingSecurityLevel value);
bool ChannelSoundingSecurityLevel_Parse(absl::string_view name, ChannelSoundingSecurityLevel* value);
enum BluetoothPbapClientContactDownloadStatus : int {
  DOWNLOAD_STATUS_UNSPECIFIED = 0,
  DOWNLOAD_STATUS_CANCELLED = 1,
  DOWNLOAD_STATUS_COMPLETED = 2,
  DOWNLOAD_STATUS_ERROR = 3,
};

bool BluetoothPbapClientContactDownloadStatus_IsValid(int value);
extern const uint32_t BluetoothPbapClientContactDownloadStatus_internal_data_[];
constexpr BluetoothPbapClientContactDownloadStatus BluetoothPbapClientContactDownloadStatus_MIN = static_cast<BluetoothPbapClientContactDownloadStatus>(0);
constexpr BluetoothPbapClientContactDownloadStatus BluetoothPbapClientContactDownloadStatus_MAX = static_cast<BluetoothPbapClientContactDownloadStatus>(3);
constexpr int BluetoothPbapClientContactDownloadStatus_ARRAYSIZE = 3 + 1;
const std::string& BluetoothPbapClientContactDownloadStatus_Name(BluetoothPbapClientContactDownloadStatus value);
template <typename T>
const std::string& BluetoothPbapClientContactDownloadStatus_Name(T value) {
  static_assert(std::is_same<T, BluetoothPbapClientContactDownloadStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothPbapClientContactDownloadStatus_Name().");
  return BluetoothPbapClientContactDownloadStatus_Name(static_cast<BluetoothPbapClientContactDownloadStatus>(value));
}
const std::string& BluetoothPbapClientContactDownloadStatus_Name(BluetoothPbapClientContactDownloadStatus value);
bool BluetoothPbapClientContactDownloadStatus_Parse(absl::string_view name, BluetoothPbapClientContactDownloadStatus* value);
enum BluetoothPbapClientPhonebookDownloadStatus : int {
  STATUS_UNSPECIFIED = 0,
  STATUS_SUCCESS = 1,
  STATUS_SUCCESS_CACHE_INVALIDATED = 2,
  STATUS_NOT_SUPPORTED = 3,
  STATUS_SUPPORTED_NOT_REQUESTED = 4,
  STATUS_CACHED = 5,
  STATUS_ERROR = 6,
  STATUS_ERROR_OBEX_HTTP_BAD_REQUEST = 7,
  STATUS_ERROR_OBEX_HTTP_UNAUTHORIZED = 8,
  STATUS_ERROR_OBEX_HTTP_FORBIDDEN = 9,
  STATUS_ERROR_OBEX_HTTP_NOT_FOUND = 10,
  STATUS_ERROR_OBEX_HTTP_NOT_ACCEPTABLE = 11,
  STATUS_ERROR_OBEX_HTTP_TIMEOUT = 12,
  STATUS_ERROR_OBEX_HTTP_PRECON_FAILED = 13,
  STATUS_ERROR_OBEX_HTTP_INTERNAL_ERROR = 14,
  STATUS_ERROR_OBEX_HTTP_NOT_IMPLEMENTED = 15,
  STATUS_ERROR_OBEX_HTTP_UNAVAILABLE = 16,
};

bool BluetoothPbapClientPhonebookDownloadStatus_IsValid(int value);
extern const uint32_t BluetoothPbapClientPhonebookDownloadStatus_internal_data_[];
constexpr BluetoothPbapClientPhonebookDownloadStatus BluetoothPbapClientPhonebookDownloadStatus_MIN = static_cast<BluetoothPbapClientPhonebookDownloadStatus>(0);
constexpr BluetoothPbapClientPhonebookDownloadStatus BluetoothPbapClientPhonebookDownloadStatus_MAX = static_cast<BluetoothPbapClientPhonebookDownloadStatus>(16);
constexpr int BluetoothPbapClientPhonebookDownloadStatus_ARRAYSIZE = 16 + 1;
const std::string& BluetoothPbapClientPhonebookDownloadStatus_Name(BluetoothPbapClientPhonebookDownloadStatus value);
template <typename T>
const std::string& BluetoothPbapClientPhonebookDownloadStatus_Name(T value) {
  static_assert(std::is_same<T, BluetoothPbapClientPhonebookDownloadStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothPbapClientPhonebookDownloadStatus_Name().");
  return BluetoothPbapClientPhonebookDownloadStatus_Name(static_cast<BluetoothPbapClientPhonebookDownloadStatus>(value));
}
const std::string& BluetoothPbapClientPhonebookDownloadStatus_Name(BluetoothPbapClientPhonebookDownloadStatus value);
bool BluetoothPbapClientPhonebookDownloadStatus_Parse(absl::string_view name, BluetoothPbapClientPhonebookDownloadStatus* value);
enum BluetoothPbapClientPhonebookType : int {
  PHONEBOOK_UNSPECIFIED = 0,
  PHONEBOOK_LOCAL = 1,
  PHONEBOOK_FAVORITES = 2,
  PHONEBOOK_MCH = 3,
  PHONEBOOK_ICH = 4,
  PHONEBOOK_OCH = 5,
  PHONEBOOK_SIM = 6,
  PHONEBOOK_SIM_MCH = 7,
  PHONEBOOK_SIM_ICH = 8,
  PHONEBOOK_SIM_OCH = 9,
};

bool BluetoothPbapClientPhonebookType_IsValid(int value);
extern const uint32_t BluetoothPbapClientPhonebookType_internal_data_[];
constexpr BluetoothPbapClientPhonebookType BluetoothPbapClientPhonebookType_MIN = static_cast<BluetoothPbapClientPhonebookType>(0);
constexpr BluetoothPbapClientPhonebookType BluetoothPbapClientPhonebookType_MAX = static_cast<BluetoothPbapClientPhonebookType>(9);
constexpr int BluetoothPbapClientPhonebookType_ARRAYSIZE = 9 + 1;
const std::string& BluetoothPbapClientPhonebookType_Name(BluetoothPbapClientPhonebookType value);
template <typename T>
const std::string& BluetoothPbapClientPhonebookType_Name(T value) {
  static_assert(std::is_same<T, BluetoothPbapClientPhonebookType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothPbapClientPhonebookType_Name().");
  return BluetoothPbapClientPhonebookType_Name(static_cast<BluetoothPbapClientPhonebookType>(value));
}
const std::string& BluetoothPbapClientPhonebookType_Name(BluetoothPbapClientPhonebookType value);
bool BluetoothPbapClientPhonebookType_Parse(absl::string_view name, BluetoothPbapClientPhonebookType* value);
enum BluetoothOppSessionStatus : int {
  OPP_SESSION_STATUS_UNSPECIFIED = 0,
  OPP_SESSION_STATUS_PENDING = 1,
  OPP_SESSION_STATUS_RUNNING = 2,
  OPP_SESSION_STATUS_SUCCESS = 3,
  OPP_SESSION_STATUS_BAD_REQUEST = 4,
  OPP_SESSION_STATUS_USER_STATUS_FORBIDDEN = 5,
  OPP_SESSION_STATUS_NOT_ACCEPTABLE = 6,
  OPP_SESSION_STATUS_LENGTH_REQUIRED = 7,
  OPP_SESSION_STATUS_PRECONDITION_FAILED = 8,
  OPP_SESSION_STATUS_CANCELED = 9,
  OPP_SESSION_STATUS_UNKNOWN_ERROR = 10,
  OPP_SESSION_STATUS_FILE_ERROR = 11,
  OPP_SESSION_STATUS_ERROR_NO_SDCARD = 12,
  OPP_SESSION_STATUS_ERROR_SDCARD_FULL = 13,
  OPP_SESSION_STATUS_UNHANDLED_OBEX_CODE = 14,
  OPP_SESSION_STATUS_OBEX_DATA_ERROR = 15,
  OPP_SESSION_STATUS_CONNECTION_ERROR = 16,
  OPP_SESSION_STATUS_UNSUPPORTED_TYPE = 17,
};

bool BluetoothOppSessionStatus_IsValid(int value);
extern const uint32_t BluetoothOppSessionStatus_internal_data_[];
constexpr BluetoothOppSessionStatus BluetoothOppSessionStatus_MIN = static_cast<BluetoothOppSessionStatus>(0);
constexpr BluetoothOppSessionStatus BluetoothOppSessionStatus_MAX = static_cast<BluetoothOppSessionStatus>(17);
constexpr int BluetoothOppSessionStatus_ARRAYSIZE = 17 + 1;
const std::string& BluetoothOppSessionStatus_Name(BluetoothOppSessionStatus value);
template <typename T>
const std::string& BluetoothOppSessionStatus_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppSessionStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppSessionStatus_Name().");
  return BluetoothOppSessionStatus_Name(static_cast<BluetoothOppSessionStatus>(value));
}
const std::string& BluetoothOppSessionStatus_Name(BluetoothOppSessionStatus value);
bool BluetoothOppSessionStatus_Parse(absl::string_view name, BluetoothOppSessionStatus* value);
enum BluetoothOppTransferDirection : int {
  OPP_TRANSFER_DIRECTION_UNSPECIFIED = 0,
  OPP_TRANSFER_DIRECTION_SEND = 1,
  OPP_TRANSFER_DIRECTION_RECEIVE = 2,
};

bool BluetoothOppTransferDirection_IsValid(int value);
extern const uint32_t BluetoothOppTransferDirection_internal_data_[];
constexpr BluetoothOppTransferDirection BluetoothOppTransferDirection_MIN = static_cast<BluetoothOppTransferDirection>(0);
constexpr BluetoothOppTransferDirection BluetoothOppTransferDirection_MAX = static_cast<BluetoothOppTransferDirection>(2);
constexpr int BluetoothOppTransferDirection_ARRAYSIZE = 2 + 1;
const std::string& BluetoothOppTransferDirection_Name(BluetoothOppTransferDirection value);
template <typename T>
const std::string& BluetoothOppTransferDirection_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppTransferDirection>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppTransferDirection_Name().");
  return BluetoothOppTransferDirection_Name(static_cast<BluetoothOppTransferDirection>(value));
}
const std::string& BluetoothOppTransferDirection_Name(BluetoothOppTransferDirection value);
bool BluetoothOppTransferDirection_Parse(absl::string_view name, BluetoothOppTransferDirection* value);
enum BluetoothOppFileSize : int {
  OPP_FILE_SIZE_UNSPECIFIED = 0,
  OPP_FILE_SIZE_UNDER_1_KB = 1,
  OPP_FILE_SIZE_1KB_TO_2KB = 2,
  OPP_FILE_SIZE_2KB_TO_4KB = 3,
  OPP_FILE_SIZE_4KB_TO_8KB = 4,
  OPP_FILE_SIZE_8KB_TO_16KB = 5,
  OPP_FILE_SIZE_16KB_TO_32KB = 6,
  OPP_FILE_SIZE_32KB_TO_64KB = 7,
  OPP_FILE_SIZE_64KB_TO_128KB = 8,
  OPP_FILE_SIZE_128KB_TO_256KB = 9,
  OPP_FILE_SIZE_256KB_TO_512KB = 10,
  OPP_FILE_SIZE_512KB_TO_1MB = 11,
  OPP_FILE_SIZE_1MB_TO_2MB = 12,
  OPP_FILE_SIZE_2MB_TO_4MB = 13,
  OPP_FILE_SIZE_4MB_TO_8MB = 14,
  OPP_FILE_SIZE_8MB_TO_16MB = 15,
  OPP_FILE_SIZE_16MB_TO_32MB = 16,
  OPP_FILE_SIZE_32MB_TO_64MB = 17,
  OPP_FILE_SIZE_64MB_TO_128MB = 18,
  OPP_FILE_SIZE_128MB_TO_256MB = 19,
  OPP_FILE_SIZE_256MB_TO_512MB = 20,
  OPP_FILE_SIZE_512MB_TO_1GB = 21,
  OPP_FILE_SIZE_1GB_TO_2GB = 22,
  OPP_FILE_SIZE_2GB_TO_4GB = 23,
  OPP_FILE_SIZE_4GB_TO_8GB = 24,
  OPP_FILE_SIZE_ABOVE_8GB = 25,
};

bool BluetoothOppFileSize_IsValid(int value);
extern const uint32_t BluetoothOppFileSize_internal_data_[];
constexpr BluetoothOppFileSize BluetoothOppFileSize_MIN = static_cast<BluetoothOppFileSize>(0);
constexpr BluetoothOppFileSize BluetoothOppFileSize_MAX = static_cast<BluetoothOppFileSize>(25);
constexpr int BluetoothOppFileSize_ARRAYSIZE = 25 + 1;
const std::string& BluetoothOppFileSize_Name(BluetoothOppFileSize value);
template <typename T>
const std::string& BluetoothOppFileSize_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppFileSize>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppFileSize_Name().");
  return BluetoothOppFileSize_Name(static_cast<BluetoothOppFileSize>(value));
}
const std::string& BluetoothOppFileSize_Name(BluetoothOppFileSize value);
bool BluetoothOppFileSize_Parse(absl::string_view name, BluetoothOppFileSize* value);
enum BluetoothOppTransferDuration : int {
  OPP_TRANSFER_DURATION_UNSPECIFIED = 0,
  OPP_TRANSFER_DURATION_UNDER_1_SEC = 1,
  OPP_TRANSFER_DURATION_1_TO_5_SEC = 2,
  OPP_TRANSFER_DURATION_5_TO_30_SEC = 3,
  OPP_TRANSFER_DURATION_30_TO_60_SEC = 4,
  OPP_TRANSFER_DURATION_1_TO_5_MIN = 5,
  OPP_TRANSFER_DURATION_5_TO_15_MIN = 6,
  OPP_TRANSFER_DURATION_15_TO_30_MIN = 7,
  OPP_TRANSFER_DURATION_ABOVE_30_MIN = 8,
};

bool BluetoothOppTransferDuration_IsValid(int value);
extern const uint32_t BluetoothOppTransferDuration_internal_data_[];
constexpr BluetoothOppTransferDuration BluetoothOppTransferDuration_MIN = static_cast<BluetoothOppTransferDuration>(0);
constexpr BluetoothOppTransferDuration BluetoothOppTransferDuration_MAX = static_cast<BluetoothOppTransferDuration>(8);
constexpr int BluetoothOppTransferDuration_ARRAYSIZE = 8 + 1;
const std::string& BluetoothOppTransferDuration_Name(BluetoothOppTransferDuration value);
template <typename T>
const std::string& BluetoothOppTransferDuration_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppTransferDuration>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppTransferDuration_Name().");
  return BluetoothOppTransferDuration_Name(static_cast<BluetoothOppTransferDuration>(value));
}
const std::string& BluetoothOppTransferDuration_Name(BluetoothOppTransferDuration value);
bool BluetoothOppTransferDuration_Parse(absl::string_view name, BluetoothOppTransferDuration* value);
enum BluetoothOppTransferSpeed : int {
  OPP_TRANSFER_SPEED_UNSPECIFIED = 0,
  OPP_TRANSFER_SPEED_UNDER_10_KBPS = 1,
  OPP_TRANSFER_SPEED_10_TO_50_KBPS = 2,
  OPP_TRANSFER_SPEED_50_TO_100_KBPS = 3,
  OPP_TRANSFER_SPEED_100_TO_175_KBPS = 4,
  OPP_TRANSFER_SPEED_175_TO_250_KBPS = 5,
  OPP_TRANSFER_SPEED_250_TO_500_KBPS = 6,
  OPP_TRANSFER_SPEED_ABOVE_500_KBPS = 7,
};

bool BluetoothOppTransferSpeed_IsValid(int value);
extern const uint32_t BluetoothOppTransferSpeed_internal_data_[];
constexpr BluetoothOppTransferSpeed BluetoothOppTransferSpeed_MIN = static_cast<BluetoothOppTransferSpeed>(0);
constexpr BluetoothOppTransferSpeed BluetoothOppTransferSpeed_MAX = static_cast<BluetoothOppTransferSpeed>(7);
constexpr int BluetoothOppTransferSpeed_ARRAYSIZE = 7 + 1;
const std::string& BluetoothOppTransferSpeed_Name(BluetoothOppTransferSpeed value);
template <typename T>
const std::string& BluetoothOppTransferSpeed_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppTransferSpeed>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppTransferSpeed_Name().");
  return BluetoothOppTransferSpeed_Name(static_cast<BluetoothOppTransferSpeed>(value));
}
const std::string& BluetoothOppTransferSpeed_Name(BluetoothOppTransferSpeed value);
bool BluetoothOppTransferSpeed_Parse(absl::string_view name, BluetoothOppTransferSpeed* value);
enum BluetoothOppMimeTypeCategory : int {
  OPP_MIME_TYPE_CATEGORY_UNSPECIFIED = 0,
  OPP_MIME_TYPE_CATEGORY_IMAGE = 1,
  OPP_MIME_TYPE_CATEGORY_VIDEO = 2,
  OPP_MIME_TYPE_CATEGORY_AUDIO = 3,
  OPP_MIME_TYPE_CATEGORY_DOCUMENT = 5,
  OPP_MIME_TYPE_CATEGORY_COMPRESSED = 6,
  OPP_MIME_TYPE_CATEGORY_OTHER = 7,
};

bool BluetoothOppMimeTypeCategory_IsValid(int value);
extern const uint32_t BluetoothOppMimeTypeCategory_internal_data_[];
constexpr BluetoothOppMimeTypeCategory BluetoothOppMimeTypeCategory_MIN = static_cast<BluetoothOppMimeTypeCategory>(0);
constexpr BluetoothOppMimeTypeCategory BluetoothOppMimeTypeCategory_MAX = static_cast<BluetoothOppMimeTypeCategory>(7);
constexpr int BluetoothOppMimeTypeCategory_ARRAYSIZE = 7 + 1;
const std::string& BluetoothOppMimeTypeCategory_Name(BluetoothOppMimeTypeCategory value);
template <typename T>
const std::string& BluetoothOppMimeTypeCategory_Name(T value) {
  static_assert(std::is_same<T, BluetoothOppMimeTypeCategory>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BluetoothOppMimeTypeCategory_Name().");
  return BluetoothOppMimeTypeCategory_Name(static_cast<BluetoothOppMimeTypeCategory>(value));
}
const std::string& BluetoothOppMimeTypeCategory_Name(BluetoothOppMimeTypeCategory value);
bool BluetoothOppMimeTypeCategory_Parse(absl::string_view name, BluetoothOppMimeTypeCategory* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::ConnectionStateEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::EnableDisableReasonEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::DirectionEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::LinkTypeEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::DeviceInfoSrcEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::DeviceTypeEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::TransportTypeEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BondStateEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BondSubStateEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::UnbondReasonEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::SocketTypeEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::SocketConnectionstateEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::SocketRoleEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::SocketErrorEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::L2capCocConnectionResult> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::CodePathCounterKeyEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::AddressTypeEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::MajorClassEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ProfileConnectionResult> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ProfileConnectionReason> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::LeConnectionResult> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ContentProfileFileName> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::EventType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::State> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::RemoteDeviceTypeMetadata> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BroadcastAudioQualityType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BroadcastSessionSetupStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BroadcastSyncStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BtaStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ChannelSoundingType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ChannelSoundingStopReason> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::ChannelSoundingSecurityLevel> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothPbapClientContactDownloadStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothPbapClientPhonebookDownloadStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothPbapClientPhonebookType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppSessionStatus> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppTransferDirection> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppFileSize> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppTransferDuration> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppTransferSpeed> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::BluetoothOppMimeTypeCategory> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fenums_2eproto_2epb_2eh
