// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::A2dp {

std::optional<bool> src_sink_coexist();

}  // namespace android::sysprop::bluetooth::A2dp
