// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Avrcp {

std::optional<bool> absolute_volume();

std::optional<std::int32_t> target_safe_media_volume();

}  // namespace android::sysprop::bluetooth::Avrcp
