// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Ble {

std::optional<bool> vnd_included();

std::optional<std::int32_t> random_address_rotation_interval_min();

std::optional<std::int32_t> random_address_rotation_interval_max();

std::optional<bool> allow_enc_with_bredr();

}  // namespace android::sysprop::bluetooth::Ble
