// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Bta {

std::optional<std::int32_t> disable_delay();

}  // namespace android::sysprop::bluetooth::Bta
