// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Core {

std::optional<bool> getLeVendorCapabilitiesEnabled();

std::optional<bool> le_rpa_offload();

std::optional<bool> isMsftHciExtEnabled();

std::optional<std::uint32_t> getLeDirectConnectionTimeout();

std::optional<std::uint32_t> getLeConnectionScanIntervalFast();

std::optional<std::uint32_t> getLeConnectionScanWindowFast();

std::optional<std::uint32_t> getLeConnectionScanWindow2mFast();

std::optional<std::uint32_t> getLeConnectionScanWindowCodedFast();

std::optional<std::uint32_t> getLeConnectionScanIntervalSlow();

std::optional<std::uint32_t> getLeConnectionScanWindowSlow();

std::optional<std::uint32_t> getLeInquiryScanInterval();

std::optional<std::uint32_t> getLeInquiryScanWindow();

std::optional<bool> isGapLeConnOnlyInit1mPhyEnabled();

std::optional<std::uint32_t> getLinkSupervisionTimeout();

std::optional<std::uint32_t> getClassicPageScanType();

std::optional<std::uint32_t> getClassicPageScanInterval();

std::optional<std::uint32_t> getClassicPageScanWindow();

std::optional<std::uint32_t> getClassicInquiryScanType();

std::optional<std::uint32_t> getClassicInquiryScanInterval();

std::optional<std::uint32_t> getClassicInquiryScanWindow();

std::optional<std::uint32_t> getClassicPageTimeout();

}  // namespace android::sysprop::bluetooth::Core
