// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::DeviceIDProperties {

std::optional<std::int32_t> vendor_id();

std::optional<std::int32_t> vendor_id_source();

std::optional<std::int32_t> product_id();

}  // namespace android::sysprop::bluetooth::DeviceIDProperties
