// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Gap {

std::optional<std::int32_t> min_key_size();

}  // namespace android::sysprop::bluetooth::Gap
