// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::hardware {

std::optional<bool> wakeup_supported();

}  // namespace android::sysprop::bluetooth::hardware
