// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Hci {

std::optional<std::int32_t> msft_vendor_opcode();

}  // namespace android::sysprop::bluetooth::Hci
