// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Hfp {

std::optional<std::int32_t> hf_client_features();

std::optional<std::int32_t> hf_features();

std::optional<std::int32_t> hf_services();

std::optional<std::int32_t> version();

std::optional<bool> codec_aptx_voice();

std::optional<bool> swb_aptx_power_management();

std::optional<bool> answer_call_with_video();

std::optional<bool> send_ringtone_on_dnd();

}  // namespace android::sysprop::bluetooth::Hfp
