// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::LeAudio {

std::optional<bool> is_software_datapath_supported_test();

std::optional<bool> is_dynamic_direction_opening_supported_test();

std::optional<bool> iso_interleaved_packing_enabled();

}  // namespace android::sysprop::bluetooth::LeAudio
