// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::bluetooth::Tmap {

std::optional<bool> isProfileTmapCallGatewayEnabled();

std::optional<bool> isProfileTmapUnicastMediaSenderEnabled();

std::optional<bool> isProfileTmapBroadcastMediaSenderEnabled();

}  // namespace android::sysprop::bluetooth::Tmap
