// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/a2dp/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fa2dp_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fa2dp_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fa2dp_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fa2dp_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
namespace a2dp {
enum PlaybackStateEnum : int {
  PLAYBACK_STATE_UNKNOWN = 0,
  PLAYBACK_STATE_PLAYING = 10,
  PLAYBACK_STATE_NOT_PLAYING = 11,
};

bool PlaybackStateEnum_IsValid(int value);
extern const uint32_t PlaybackStateEnum_internal_data_[];
constexpr PlaybackStateEnum PlaybackStateEnum_MIN = static_cast<PlaybackStateEnum>(0);
constexpr PlaybackStateEnum PlaybackStateEnum_MAX = static_cast<PlaybackStateEnum>(11);
constexpr int PlaybackStateEnum_ARRAYSIZE = 11 + 1;
const std::string& PlaybackStateEnum_Name(PlaybackStateEnum value);
template <typename T>
const std::string& PlaybackStateEnum_Name(T value) {
  static_assert(std::is_same<T, PlaybackStateEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PlaybackStateEnum_Name().");
  return PlaybackStateEnum_Name(static_cast<PlaybackStateEnum>(value));
}
const std::string& PlaybackStateEnum_Name(PlaybackStateEnum value);
bool PlaybackStateEnum_Parse(absl::string_view name, PlaybackStateEnum* value);
enum AudioCodingModeEnum : int {
  AUDIO_CODING_MODE_UNKNOWN = 0,
  AUDIO_CODING_MODE_HARDWARE = 1,
  AUDIO_CODING_MODE_SOFTWARE = 2,
};

bool AudioCodingModeEnum_IsValid(int value);
extern const uint32_t AudioCodingModeEnum_internal_data_[];
constexpr AudioCodingModeEnum AudioCodingModeEnum_MIN = static_cast<AudioCodingModeEnum>(0);
constexpr AudioCodingModeEnum AudioCodingModeEnum_MAX = static_cast<AudioCodingModeEnum>(2);
constexpr int AudioCodingModeEnum_ARRAYSIZE = 2 + 1;
const std::string& AudioCodingModeEnum_Name(AudioCodingModeEnum value);
template <typename T>
const std::string& AudioCodingModeEnum_Name(T value) {
  static_assert(std::is_same<T, AudioCodingModeEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AudioCodingModeEnum_Name().");
  return AudioCodingModeEnum_Name(static_cast<AudioCodingModeEnum>(value));
}
const std::string& AudioCodingModeEnum_Name(AudioCodingModeEnum value);
bool AudioCodingModeEnum_Parse(absl::string_view name, AudioCodingModeEnum* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace a2dp
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::a2dp::PlaybackStateEnum> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::a2dp::AudioCodingModeEnum> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fa2dp_2fenums_2eproto_2epb_2eh
