// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/a2dp/enums.proto

#include "frameworks/proto_logging/stats/enums/bluetooth/a2dp/enums.pb.h"

#include <algorithm>
#include <cstdint>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace android {
namespace bluetooth {
namespace a2dp {
}  // namespace a2dp
}  // namespace bluetooth
}  // namespace android
namespace android {
namespace bluetooth {
namespace a2dp {
PROTOBUF_CONSTINIT const uint32_t PlaybackStateEnum_internal_data_[] = {
    65536u, 32u, 1536u, };
bool PlaybackStateEnum_IsValid(int value) {
  return 0 <= value && value <= 11 && ((3073u >> value) & 1) != 0;
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    PlaybackStateEnum_strings[3] = {};

static const char PlaybackStateEnum_names[] = {
    "PLAYBACK_STATE_NOT_PLAYING"
    "PLAYBACK_STATE_PLAYING"
    "PLAYBACK_STATE_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry PlaybackStateEnum_entries[] =
    {
        {{&PlaybackStateEnum_names[0], 26}, 11},
        {{&PlaybackStateEnum_names[26], 22}, 10},
        {{&PlaybackStateEnum_names[48], 22}, 0},
};

static const int PlaybackStateEnum_entries_by_number[] = {
    2,  // 0 -> PLAYBACK_STATE_UNKNOWN
    1,  // 10 -> PLAYBACK_STATE_PLAYING
    0,  // 11 -> PLAYBACK_STATE_NOT_PLAYING
};

const std::string& PlaybackStateEnum_Name(PlaybackStateEnum value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          PlaybackStateEnum_entries, PlaybackStateEnum_entries_by_number,
          3, PlaybackStateEnum_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      PlaybackStateEnum_entries, PlaybackStateEnum_entries_by_number, 3,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : PlaybackStateEnum_strings[idx].get();
}

bool PlaybackStateEnum_Parse(absl::string_view name, PlaybackStateEnum* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      PlaybackStateEnum_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<PlaybackStateEnum>(int_value);
  }
  return success;
}
PROTOBUF_CONSTINIT const uint32_t AudioCodingModeEnum_internal_data_[] = {
    196608u, 0u, };
bool AudioCodingModeEnum_IsValid(int value) {
  return 0 <= value && value <= 2;
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    AudioCodingModeEnum_strings[3] = {};

static const char AudioCodingModeEnum_names[] = {
    "AUDIO_CODING_MODE_HARDWARE"
    "AUDIO_CODING_MODE_SOFTWARE"
    "AUDIO_CODING_MODE_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry AudioCodingModeEnum_entries[] =
    {
        {{&AudioCodingModeEnum_names[0], 26}, 1},
        {{&AudioCodingModeEnum_names[26], 26}, 2},
        {{&AudioCodingModeEnum_names[52], 25}, 0},
};

static const int AudioCodingModeEnum_entries_by_number[] = {
    2,  // 0 -> AUDIO_CODING_MODE_UNKNOWN
    0,  // 1 -> AUDIO_CODING_MODE_HARDWARE
    1,  // 2 -> AUDIO_CODING_MODE_SOFTWARE
};

const std::string& AudioCodingModeEnum_Name(AudioCodingModeEnum value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          AudioCodingModeEnum_entries, AudioCodingModeEnum_entries_by_number,
          3, AudioCodingModeEnum_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      AudioCodingModeEnum_entries, AudioCodingModeEnum_entries_by_number, 3,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : AudioCodingModeEnum_strings[idx].get();
}

bool AudioCodingModeEnum_Parse(absl::string_view name, AudioCodingModeEnum* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      AudioCodingModeEnum_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<AudioCodingModeEnum>(int_value);
  }
  return success;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace a2dp
}  // namespace bluetooth
}  // namespace android
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
