// Generated by the sysprop generator. DO NOT EDIT!

#include <android/sysprop/BluetoothProperties.sysprop.h>

#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <limits>
#include <utility>

#include <strings.h>
#ifdef __BIONIC__
#include <sys/system_properties.h>
[[maybe_unused]] static bool SetProp(const char* key, const char* value) {
    return __system_property_set(key, value) == 0;
}
#else
#include <android-base/properties.h>
[[maybe_unused]] static bool SetProp(const char* key, const char* value) {
    android::base::SetProperty(key, value);
    return true;
}
#endif

#include <android-base/parseint.h>
#include <log/log.h>

namespace {

using namespace android::sysprop::BluetoothProperties;

template <typename T> T DoParse(const char* str);

constexpr const std::pair<const char*, snoop_default_mode_values> snoop_default_mode_list[] = {
    {"empty", snoop_default_mode_values::EMPTY},
    {"disabled", snoop_default_mode_values::DISABLED},
    {"filtered", snoop_default_mode_values::FILTERED},
    {"full", snoop_default_mode_values::FULL},
};

template <>
std::optional<snoop_default_mode_values> DoParse(const char* str) {
    for (auto [name, val] : snoop_default_mode_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

std::string FormatValue(std::optional<snoop_default_mode_values> value) {
    if (!value) return "";
    for (auto [name, val] : snoop_default_mode_list) {
        if (val == *value) {
            return name;
        }
    }
    LOG_ALWAYS_FATAL("Invalid value %d for property persist.bluetooth.btsnoopdefaultmode", static_cast<std::int32_t>(*value));
    __builtin_unreachable();
}

constexpr const std::pair<const char*, snoop_log_mode_values> snoop_log_mode_list[] = {
    {"empty", snoop_log_mode_values::EMPTY},
    {"disabled", snoop_log_mode_values::DISABLED},
    {"filtered", snoop_log_mode_values::FILTERED},
    {"full", snoop_log_mode_values::FULL},
};

template <>
std::optional<snoop_log_mode_values> DoParse(const char* str) {
    for (auto [name, val] : snoop_log_mode_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

std::string FormatValue(std::optional<snoop_log_mode_values> value) {
    if (!value) return "";
    for (auto [name, val] : snoop_log_mode_list) {
        if (val == *value) {
            return name;
        }
    }
    LOG_ALWAYS_FATAL("Invalid value %d for property persist.bluetooth.btsnooplogmode", static_cast<std::int32_t>(*value));
    __builtin_unreachable();
}

constexpr const std::pair<const char*, snoop_log_filter_profile_map_values> snoop_log_filter_profile_map_list[] = {
    {"empty", snoop_log_filter_profile_map_values::EMPTY},
    {"disabled", snoop_log_filter_profile_map_values::DISABLED},
    {"fullfilter", snoop_log_filter_profile_map_values::FULLFILTER},
    {"header", snoop_log_filter_profile_map_values::HEADER},
    {"magic", snoop_log_filter_profile_map_values::MAGIC},
};

template <>
std::optional<snoop_log_filter_profile_map_values> DoParse(const char* str) {
    for (auto [name, val] : snoop_log_filter_profile_map_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

std::string FormatValue(std::optional<snoop_log_filter_profile_map_values> value) {
    if (!value) return "";
    for (auto [name, val] : snoop_log_filter_profile_map_list) {
        if (val == *value) {
            return name;
        }
    }
    LOG_ALWAYS_FATAL("Invalid value %d for property persist.bluetooth.snooplogfilter.profiles.map", static_cast<std::int32_t>(*value));
    __builtin_unreachable();
}

constexpr const std::pair<const char*, snoop_log_filter_profile_pbap_values> snoop_log_filter_profile_pbap_list[] = {
    {"empty", snoop_log_filter_profile_pbap_values::EMPTY},
    {"disabled", snoop_log_filter_profile_pbap_values::DISABLED},
    {"fullfilter", snoop_log_filter_profile_pbap_values::FULLFILTER},
    {"header", snoop_log_filter_profile_pbap_values::HEADER},
    {"magic", snoop_log_filter_profile_pbap_values::MAGIC},
};

template <>
std::optional<snoop_log_filter_profile_pbap_values> DoParse(const char* str) {
    for (auto [name, val] : snoop_log_filter_profile_pbap_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

std::string FormatValue(std::optional<snoop_log_filter_profile_pbap_values> value) {
    if (!value) return "";
    for (auto [name, val] : snoop_log_filter_profile_pbap_list) {
        if (val == *value) {
            return name;
        }
    }
    LOG_ALWAYS_FATAL("Invalid value %d for property persist.bluetooth.snooplogfilter.profiles.pbap", static_cast<std::int32_t>(*value));
    __builtin_unreachable();
}

template <typename T> constexpr bool is_vector = false;

template <typename T> constexpr bool is_vector<std::vector<T>> = true;

template <> [[maybe_unused]] std::optional<bool> DoParse(const char* str) {
    static constexpr const char* kYes[] = {"1", "true"};
    static constexpr const char* kNo[] = {"0", "false"};

    for (const char* yes : kYes) {
        if (strcasecmp(yes, str) == 0) return std::make_optional(true);
    }

    for (const char* no : kNo) {
        if (strcasecmp(no, str) == 0) return std::make_optional(false);
    }

    return std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::int32_t> DoParse(const char* str) {
    std::int32_t ret;
    return android::base::ParseInt(str, &ret) ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::uint32_t> DoParse(const char* str) {
    std::uint32_t ret;
    return android::base::ParseUint(str, &ret) ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::int64_t> DoParse(const char* str) {
    std::int64_t ret;
    return android::base::ParseInt(str, &ret) ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::uint64_t> DoParse(const char* str) {
    std::uint64_t ret;
    return android::base::ParseUint(str, &ret) ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<double> DoParse(const char* str) {
    int old_errno = errno;
    errno = 0;
    char* end;
    double ret = std::strtod(str, &end);
    if (errno != 0) {
        return std::nullopt;
    }
    if (str == end || *end != '\0') {
        errno = EINVAL;
        return std::nullopt;
    }
    errno = old_errno;
    return std::make_optional(ret);
}

template <> [[maybe_unused]] std::optional<std::string> DoParse(const char* str) {
    return *str == '\0' ? std::nullopt : std::make_optional(str);
}

template <typename Vec> [[maybe_unused]] Vec DoParseList(const char* str) {
    Vec ret;
    if (*str == '\0') return ret;
    const char* p = str;
    for (;;) {
        const char* r = p;
        std::string value;
        while (*r != ',') {
            if (*r == '\\') ++r;
            if (*r == '\0') break;
            value += *r++;
        }
        ret.emplace_back(DoParse<typename Vec::value_type>(value.c_str()));
        if (*r == '\0') break;
        p = r + 1;
    }
    return ret;
}

template <typename T> inline T TryParse(const char* str) {
    if constexpr(is_vector<T>) {
        return DoParseList<T>(str);
    } else {
        return DoParse<T>(str);
    }
}

[[maybe_unused]] std::string FormatValue(const std::optional<std::int32_t>& value) {
    return value ? std::to_string(*value) : "";
}

[[maybe_unused]] std::string FormatValue(const std::optional<std::uint32_t>& value) {
    return value ? std::to_string(*value) : "";
}

[[maybe_unused]] std::string FormatValue(const std::optional<std::int64_t>& value) {
    return value ? std::to_string(*value) : "";
}

[[maybe_unused]] std::string FormatValue(const std::optional<std::uint64_t>& value) {
    return value ? std::to_string(*value) : "";
}

[[maybe_unused]] std::string FormatValue(const std::optional<double>& value) {
    if (!value) return "";
    char buf[1024];
    std::sprintf(buf, "%.*g", std::numeric_limits<double>::max_digits10, *value);
    return buf;
}

[[maybe_unused]] std::string FormatValue(const std::optional<bool>& value) {
    return value ? (*value ? "true" : "false") : "";
}

template <typename T>
[[maybe_unused]] std::string FormatValue(const std::vector<T>& value) {
    if (value.empty()) return "";

    std::string ret;
    bool first = true;

    for (auto&& element : value) {
        if (!first) ret += ',';
        else first = false;
        if constexpr(std::is_same_v<T, std::optional<std::string>>) {
            if (element) {
                for (char c : *element) {
                    if (c == '\\' || c == ',') ret += '\\';
                    ret += c;
                }
            }
        } else {
            ret += FormatValue(element);
        }
    }

    return ret;
}

template <typename T>
T GetProp(const char* key, const char* legacy = nullptr) {
    std::string value;
#ifdef __BIONIC__
    auto pi = __system_property_find(key);
    if (pi != nullptr) {
        __system_property_read_callback(pi, [](void* cookie, const char*, const char* value, std::uint32_t) {
            *static_cast<std::string*>(cookie) = value;
        }, &value);
    }
#else
    value = android::base::GetProperty(key, "");
#endif
    if (value.empty() && legacy) {
        ALOGV("prop %s doesn't exist; fallback to legacy prop %s", key, legacy);
        return GetProp<T>(legacy);
    }
    return TryParse<T>(value.c_str());
}

}  // namespace

namespace android::sysprop::BluetoothProperties {

std::optional<snoop_default_mode_values> snoop_default_mode() {
    return GetProp<std::optional<snoop_default_mode_values>>("persist.bluetooth.btsnoopdefaultmode");
}

bool snoop_default_mode(const std::optional<snoop_default_mode_values>& value) {
    return SetProp("persist.bluetooth.btsnoopdefaultmode", FormatValue(value).c_str());
}

std::optional<snoop_log_mode_values> snoop_log_mode() {
    return GetProp<std::optional<snoop_log_mode_values>>("persist.bluetooth.btsnooplogmode");
}

bool snoop_log_mode(const std::optional<snoop_log_mode_values>& value) {
    return SetProp("persist.bluetooth.btsnooplogmode", FormatValue(value).c_str());
}

std::optional<bool> snoop_log_filter_snoop_headers_enabled() {
    return GetProp<std::optional<bool>>("persist.bluetooth.snooplogfilter.headers.enabled");
}

bool snoop_log_filter_snoop_headers_enabled(const std::optional<bool>& value) {
    return SetProp("persist.bluetooth.snooplogfilter.headers.enabled", FormatValue(value).c_str());
}

std::optional<bool> snoop_log_filter_profile_a2dp_enabled() {
    return GetProp<std::optional<bool>>("persist.bluetooth.snooplogfilter.profiles.a2dp.enabled");
}

bool snoop_log_filter_profile_a2dp_enabled(const std::optional<bool>& value) {
    return SetProp("persist.bluetooth.snooplogfilter.profiles.a2dp.enabled", FormatValue(value).c_str());
}

std::optional<snoop_log_filter_profile_map_values> snoop_log_filter_profile_map() {
    return GetProp<std::optional<snoop_log_filter_profile_map_values>>("persist.bluetooth.snooplogfilter.profiles.map");
}

bool snoop_log_filter_profile_map(const std::optional<snoop_log_filter_profile_map_values>& value) {
    return SetProp("persist.bluetooth.snooplogfilter.profiles.map", FormatValue(value).c_str());
}

std::optional<snoop_log_filter_profile_pbap_values> snoop_log_filter_profile_pbap() {
    return GetProp<std::optional<snoop_log_filter_profile_pbap_values>>("persist.bluetooth.snooplogfilter.profiles.pbap");
}

bool snoop_log_filter_profile_pbap(const std::optional<snoop_log_filter_profile_pbap_values>& value) {
    return SetProp("persist.bluetooth.snooplogfilter.profiles.pbap", FormatValue(value).c_str());
}

std::optional<bool> snoop_log_filter_profile_rfcomm_enabled() {
    return GetProp<std::optional<bool>>("persist.bluetooth.snooplogfilter.profiles.rfcomm.enabled");
}

bool snoop_log_filter_profile_rfcomm_enabled(const std::optional<bool>& value) {
    return SetProp("persist.bluetooth.snooplogfilter.profiles.rfcomm.enabled", FormatValue(value).c_str());
}

std::optional<bool> factory_reset() {
    return GetProp<std::optional<bool>>("persist.bluetooth.factoryreset");
}

bool factory_reset(const std::optional<bool>& value) {
    return SetProp("persist.bluetooth.factoryreset", FormatValue(value).c_str());
}

std::vector<std::optional<std::string>> le_audio_allow_list() {
    return GetProp<std::vector<std::optional<std::string>>>("persist.bluetooth.leaudio.allow_list");
}

bool le_audio_allow_list(const std::vector<std::optional<std::string>>& value) {
    return SetProp("persist.bluetooth.leaudio.allow_list", FormatValue(value).c_str());
}

std::optional<std::string> le_audio_dynamic_switcher_mode() {
    return GetProp<std::optional<std::string>>("persist.bluetooth.leaudio_dynamic_switcher.mode");
}

bool le_audio_dynamic_switcher_mode(const std::optional<std::string>& value) {
    return SetProp("persist.bluetooth.leaudio_dynamic_switcher.mode", value ? value->c_str() : "");
}

std::optional<bool> isProfileHidDeviceRuntimeDisabled() {
    return GetProp<std::optional<bool>>("persist.bluetooth.hid.device.disabled");
}

bool isProfileHidDeviceRuntimeDisabled(const std::optional<bool>& value) {
    return SetProp("persist.bluetooth.hid.device.disabled", FormatValue(value).c_str());
}

std::optional<bool> isGapLePrivacyEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.core.gap.le.privacy.enabled");
}

std::optional<std::int32_t> getGapLeConnMinLimit() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.core.gap.le.conn.min.limit");
}

std::optional<bool> isLeAudioInbandRingtoneSupported() {
    return GetProp<std::optional<bool>>("bluetooth.core.le_audio.inband_ringtone.supported");
}

std::optional<bool> isLeAudioCodecExtensionAidlEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.core.le_audio.codec_extension_aidl.enabled");
}

std::optional<std::string> getDefaultDeviceName() {
    return GetProp<std::optional<std::string>>("bluetooth.device.default_name");
}

std::vector<std::optional<std::uint32_t>> getClassOfDevice() {
    return GetProp<std::vector<std::optional<std::uint32_t>>>("bluetooth.device.class_of_device");
}

std::optional<std::int32_t> getDefaultOutputOnlyAudioProfile() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.device.default_output_only_audio_profile");
}

std::optional<std::int32_t> getDefaultDuplexAudioProfile() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.device.default_duplex_audio_profile");
}

std::optional<std::int32_t> getHardwareOperatingVoltageMv() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.hardware.power.operating_voltage_mv");
}

std::optional<std::int32_t> getHardwareIdleCurrentMa() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.hardware.power.idle_cur_ma");
}

std::optional<std::int32_t> getHardwareTxCurrentMa() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.hardware.power.tx_cur_ma");
}

std::optional<std::int32_t> getHardwareRxCurrentMa() {
    return GetProp<std::optional<std::int32_t>>("bluetooth.hardware.power.rx_cur_ma");
}

std::optional<bool> isSupportPersistedStateEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.framework.support_persisted_state");
}

std::optional<bool> isAdapterAddressValidationEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.framework.adapter_address_validation");
}

std::optional<bool> isProfileA2dpSinkEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.a2dp.sink.enabled");
}

std::optional<bool> isProfileA2dpSourceEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.a2dp.source.enabled");
}

std::optional<bool> isProfileAshaCentralEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.asha.central.enabled");
}

std::optional<bool> isProfileAvrcpControllerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.avrcp.controller.enabled");
}

std::optional<bool> isProfileAvrcpTargetEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.avrcp.target.enabled");
}

std::optional<bool> isProfileBapBroadcastAssistEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.bap.broadcast.assist.enabled");
}

std::optional<bool> isProfileBapBroadcastSourceEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.bap.broadcast.source.enabled");
}

std::optional<bool> isProfileBapUnicastClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.bap.unicast.client.enabled");
}

std::optional<bool> isProfileBasClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.bas.client.enabled");
}

std::optional<bool> isProfileBassClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.bass.client.enabled");
}

std::optional<bool> isProfileCsipSetCoordinatorEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.csip.set_coordinator.enabled");
}

std::optional<bool> isProfileGattEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.gatt.enabled");
}

std::optional<bool> isProfileGmapEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.gmap.enabled");
}

std::optional<bool> isProfileHapClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.hap.client.enabled");
}

std::optional<bool> isProfileHfpAgEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.hfp.ag.enabled");
}

std::optional<bool> isProfileHfpHfEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.hfp.hf.enabled");
}

std::optional<bool> isHfpSoftwareDatapathEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.hfp.software_datapath.enabled");
}

std::optional<bool> isProfileHidDeviceEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.hid.device.enabled");
}

std::optional<bool> isProfileHidHostEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.hid.host.enabled");
}

std::optional<bool> isProfileMapClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.map.client.enabled");
}

std::optional<bool> isProfileMapServerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.map.server.enabled");
}

std::optional<bool> isProfileMcpServerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.mcp.server.enabled");
}

std::optional<bool> isProfileOppEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.opp.enabled");
}

std::optional<bool> isProfilePanNapEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.pan.nap.enabled");
}

std::optional<bool> isProfilePanPanuEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.pan.panu.enabled");
}

std::optional<bool> isProfilePbapClientEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.pbap.client.enabled");
}

std::optional<bool> isProfilePbapServerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.pbap.server.enabled");
}

std::optional<bool> isProfilePbapSimEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.pbap.sim.enabled");
}

std::optional<bool> isProfileSapServerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.sap.server.enabled");
}

std::optional<bool> isProfileCcpServerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.ccp.server.enabled");
}

std::optional<bool> isProfileVcpControllerEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.profile.vcp.controller.enabled");
}

std::vector<std::optional<std::uint32_t>> getClassicSniffMaxIntervals() {
    return GetProp<std::vector<std::optional<std::uint32_t>>>("bluetooth.core.classic.sniff_max_intervals");
}

std::vector<std::optional<std::uint32_t>> getClassicSniffMinIntervals() {
    return GetProp<std::vector<std::optional<std::uint32_t>>>("bluetooth.core.classic.sniff_min_intervals");
}

std::vector<std::optional<std::uint32_t>> getClassicSniffAttempts() {
    return GetProp<std::vector<std::optional<std::uint32_t>>>("bluetooth.core.classic.sniff_attempts");
}

std::vector<std::optional<std::uint32_t>> getClassicSniffTimeouts() {
    return GetProp<std::vector<std::optional<std::uint32_t>>>("bluetooth.core.classic.sniff_timeouts");
}

std::optional<std::uint32_t> getLeMinConnectionInterval() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.min_connection_interval");
}

std::optional<std::uint32_t> getLeMaxConnectionInterval() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.max_connection_interval");
}

std::optional<std::uint32_t> getLeConnectionLatency() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.connection_latency");
}

std::optional<std::uint32_t> getLeConnectionSupervisionTimeout() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.connection_supervision_timeout");
}

std::optional<std::uint32_t> getLeMinConnectionIntervalRelaxed() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.min_connection_interval_relaxed");
}

std::optional<std::uint32_t> getLeMaxConnectionIntervalRelaxed() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.max_connection_interval_relaxed");
}

std::optional<std::uint32_t> getLeMinConnectionIntervalAggressive() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.min_connection_interval_aggressive");
}

std::optional<std::uint32_t> getLeMaxConnectionIntervalAggressive() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.max_connection_interval_aggressive");
}

std::optional<std::uint32_t> getLeAggressiveConnectionThreshold() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.aggressive_connection_threshold");
}

std::optional<std::uint32_t> getLeMaxNumberOfConcurrentConnections() {
    return GetProp<std::optional<std::uint32_t>>("bluetooth.core.le.max_number_of_concurrent_connections");
}

std::vector<std::optional<std::string>> dsa_transport_preference() {
    return GetProp<std::vector<std::optional<std::string>>>("bluetooth.core.le.dsa_transport_preference");
}

std::optional<bool> isScoManagedByAudioEnabled() {
    return GetProp<std::optional<bool>>("bluetooth.sco.managed_by_audio");
}

std::optional<bool> enable_sniff_offload() {
    return GetProp<std::optional<bool>>("persist.bluetooth.sniff_offload.enabled");
}

}  // namespace android::sysprop::BluetoothProperties
