// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/hfp/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fhfp_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fhfp_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fhfp_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fhfp_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
namespace hfp {
enum ScoCodec : int {
  SCO_CODEC_UNKNOWN = 0,
  SCO_CODEC_CVSD = 1,
  SCO_CODEC_MSBC = 2,
  SCO_CODEC_LC3 = 3,
};

bool ScoCodec_IsValid(int value);
extern const uint32_t ScoCodec_internal_data_[];
constexpr ScoCodec ScoCodec_MIN = static_cast<ScoCodec>(0);
constexpr ScoCodec ScoCodec_MAX = static_cast<ScoCodec>(3);
constexpr int ScoCodec_ARRAYSIZE = 3 + 1;
const std::string& ScoCodec_Name(ScoCodec value);
template <typename T>
const std::string& ScoCodec_Name(T value) {
  static_assert(std::is_same<T, ScoCodec>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ScoCodec_Name().");
  return ScoCodec_Name(static_cast<ScoCodec>(value));
}
const std::string& ScoCodec_Name(ScoCodec value);
bool ScoCodec_Parse(absl::string_view name, ScoCodec* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace hfp
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::hfp::ScoCodec> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fhfp_2fenums_2eproto_2epb_2eh
