// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/rfcomm/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2frfcomm_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2frfcomm_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2frfcomm_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2frfcomm_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
namespace rfcomm {
enum RfcommConnectionResult : int {
  RFCOMM_CONN_RESULT_FAILURE_UNKNOWN = 0,
  RFCOMM_CONN_RESULT_SUCCESS = 1,
  RFCOMM_CONN_RESULT_SOCKET_CONNECTION_FAILED = 2,
  RFCOMM_CONN_RESULT_SOCKET_CONNECTION_CLOSED = 3,
  RFCOMM_CONN_RESULT_UNABLE_TO_SEND_RPC = 4,
  RFCOMM_CONN_RESULT_NULL_BLUETOOTH_DEVICE = 5,
  RFCOMM_CONN_RESULT_GET_SOCKET_MANAGER_FAILED = 6,
  RFCOMM_CONN_RESULT_NULL_FILE_DESCRIPTOR = 7,
};

bool RfcommConnectionResult_IsValid(int value);
extern const uint32_t RfcommConnectionResult_internal_data_[];
constexpr RfcommConnectionResult RfcommConnectionResult_MIN = static_cast<RfcommConnectionResult>(0);
constexpr RfcommConnectionResult RfcommConnectionResult_MAX = static_cast<RfcommConnectionResult>(7);
constexpr int RfcommConnectionResult_ARRAYSIZE = 7 + 1;
const std::string& RfcommConnectionResult_Name(RfcommConnectionResult value);
template <typename T>
const std::string& RfcommConnectionResult_Name(T value) {
  static_assert(std::is_same<T, RfcommConnectionResult>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RfcommConnectionResult_Name().");
  return RfcommConnectionResult_Name(static_cast<RfcommConnectionResult>(value));
}
const std::string& RfcommConnectionResult_Name(RfcommConnectionResult value);
bool RfcommConnectionResult_Parse(absl::string_view name, RfcommConnectionResult* value);
enum SocketConnectionSecurity : int {
  SOCKET_SECURITY_UNKNOWN = 0,
  SOCKET_SECURITY_SECURE = 1,
  SOCKET_SECURITY_INSECURE = 2,
};

bool SocketConnectionSecurity_IsValid(int value);
extern const uint32_t SocketConnectionSecurity_internal_data_[];
constexpr SocketConnectionSecurity SocketConnectionSecurity_MIN = static_cast<SocketConnectionSecurity>(0);
constexpr SocketConnectionSecurity SocketConnectionSecurity_MAX = static_cast<SocketConnectionSecurity>(2);
constexpr int SocketConnectionSecurity_ARRAYSIZE = 2 + 1;
const std::string& SocketConnectionSecurity_Name(SocketConnectionSecurity value);
template <typename T>
const std::string& SocketConnectionSecurity_Name(T value) {
  static_assert(std::is_same<T, SocketConnectionSecurity>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SocketConnectionSecurity_Name().");
  return SocketConnectionSecurity_Name(static_cast<SocketConnectionSecurity>(value));
}
const std::string& SocketConnectionSecurity_Name(SocketConnectionSecurity value);
bool SocketConnectionSecurity_Parse(absl::string_view name, SocketConnectionSecurity* value);
enum PortResult : int {
  PORT_RESULT_UNDEFINED = 0,
  PORT_RESULT_SUCCESS = 1,
  PORT_RESULT_UNKNOWN_ERROR = 2,
  PORT_RESULT_ALREADY_OPENED = 3,
  PORT_RESULT_CMD_PENDING = 4,
  PORT_RESULT_APP_NOT_REGISTERED = 5,
  PORT_RESULT_NO_MEM = 6,
  PORT_RESULT_NO_RESOURCES = 7,
  PORT_RESULT_BAD_BD_ADDR = 8,
  PORT_RESULT_BAD_HANDLE = 9,
  PORT_RESULT_NOT_OPENED = 10,
  PORT_RESULT_LINE_ERR = 11,
  PORT_RESULT_START_FAILED = 12,
  PORT_RESULT_PAR_NEG_FAILED = 13,
  PORT_RESULT_PORT_NEG_FAILED = 14,
  PORT_RESULT_SEC_FAILED = 15,
  PORT_RESULT_PEER_CONNECTION_FAILED = 16,
  PORT_RESULT_PEER_FAILED = 17,
  PORT_RESULT_PEER_TIMEOUT = 18,
  PORT_RESULT_CLOSED = 19,
  PORT_RESULT_TX_FULL = 20,
  PORT_RESULT_LOCAL_CLOSED = 21,
  PORT_RESULT_LOCAL_TIMEOUT = 22,
  PORT_RESULT_TX_QUEUE_DISABLED = 23,
  PORT_RESULT_PAGE_TIMEOUT = 24,
  PORT_RESULT_INVALID_SCN = 25,
  PORT_RESULT_ERR_MAX = 26,
};

bool PortResult_IsValid(int value);
extern const uint32_t PortResult_internal_data_[];
constexpr PortResult PortResult_MIN = static_cast<PortResult>(0);
constexpr PortResult PortResult_MAX = static_cast<PortResult>(26);
constexpr int PortResult_ARRAYSIZE = 26 + 1;
const std::string& PortResult_Name(PortResult value);
template <typename T>
const std::string& PortResult_Name(T value) {
  static_assert(std::is_same<T, PortResult>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PortResult_Name().");
  return PortResult_Name(static_cast<PortResult>(value));
}
const std::string& PortResult_Name(PortResult value);
bool PortResult_Parse(absl::string_view name, PortResult* value);
enum RfcommPortState : int {
  PORT_STATE_UNKNOWN = 0,
  PORT_STATE_SABME_WAIT_UA = 1,
  PORT_STATE_ORIG_WAIT_SEC_CHECK = 2,
  PORT_STATE_TERM_WAIT_SEC_CHECK = 3,
  PORT_STATE_OPENED = 4,
  PORT_STATE_DISC_WAIT_UA = 5,
  PORT_STATE_CLOSED = 6,
};

bool RfcommPortState_IsValid(int value);
extern const uint32_t RfcommPortState_internal_data_[];
constexpr RfcommPortState RfcommPortState_MIN = static_cast<RfcommPortState>(0);
constexpr RfcommPortState RfcommPortState_MAX = static_cast<RfcommPortState>(6);
constexpr int RfcommPortState_ARRAYSIZE = 6 + 1;
const std::string& RfcommPortState_Name(RfcommPortState value);
template <typename T>
const std::string& RfcommPortState_Name(T value) {
  static_assert(std::is_same<T, RfcommPortState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RfcommPortState_Name().");
  return RfcommPortState_Name(static_cast<RfcommPortState>(value));
}
const std::string& RfcommPortState_Name(RfcommPortState value);
bool RfcommPortState_Parse(absl::string_view name, RfcommPortState* value);
enum RfcommPortEvent : int {
  PORT_EVENT_UNKNOWN = 0,
  PORT_EVENT_SABME = 1,
  PORT_EVENT_UA = 2,
  PORT_EVENT_DM = 3,
  PORT_EVENT_DISC = 4,
  PORT_EVENT_UIH = 5,
  PORT_EVENT_TIMEOUT = 6,
  PORT_EVENT_OPEN = 7,
  PORT_EVENT_ESTABLISH_RSP = 8,
  PORT_EVENT_CLOSE = 9,
  PORT_EVENT_CLEAR = 10,
  PORT_EVENT_DATA = 11,
  PORT_EVENT_SEC_COMPLETE = 12,
};

bool RfcommPortEvent_IsValid(int value);
extern const uint32_t RfcommPortEvent_internal_data_[];
constexpr RfcommPortEvent RfcommPortEvent_MIN = static_cast<RfcommPortEvent>(0);
constexpr RfcommPortEvent RfcommPortEvent_MAX = static_cast<RfcommPortEvent>(12);
constexpr int RfcommPortEvent_ARRAYSIZE = 12 + 1;
const std::string& RfcommPortEvent_Name(RfcommPortEvent value);
template <typename T>
const std::string& RfcommPortEvent_Name(T value) {
  static_assert(std::is_same<T, RfcommPortEvent>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RfcommPortEvent_Name().");
  return RfcommPortEvent_Name(static_cast<RfcommPortEvent>(value));
}
const std::string& RfcommPortEvent_Name(RfcommPortEvent value);
bool RfcommPortEvent_Parse(absl::string_view name, RfcommPortEvent* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rfcomm
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::rfcomm::RfcommConnectionResult> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::rfcomm::SocketConnectionSecurity> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::rfcomm::PortResult> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::rfcomm::RfcommPortState> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::rfcomm::RfcommPortEvent> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2frfcomm_2fenums_2eproto_2epb_2eh
