// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/le/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fle_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fle_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fle_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fle_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
namespace le {
enum LeAclConnectionState : int {
  LE_ACL_UNSPECIFIED = 0,
  LE_ACL_SUCCESS = 1,
  LE_ACL_FAILED = 2,
  LE_ACL_ALREADY_PRESENT = 3,
};

bool LeAclConnectionState_IsValid(int value);
extern const uint32_t LeAclConnectionState_internal_data_[];
constexpr LeAclConnectionState LeAclConnectionState_MIN = static_cast<LeAclConnectionState>(0);
constexpr LeAclConnectionState LeAclConnectionState_MAX = static_cast<LeAclConnectionState>(3);
constexpr int LeAclConnectionState_ARRAYSIZE = 3 + 1;
const std::string& LeAclConnectionState_Name(LeAclConnectionState value);
template <typename T>
const std::string& LeAclConnectionState_Name(T value) {
  static_assert(std::is_same<T, LeAclConnectionState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeAclConnectionState_Name().");
  return LeAclConnectionState_Name(static_cast<LeAclConnectionState>(value));
}
const std::string& LeAclConnectionState_Name(LeAclConnectionState value);
bool LeAclConnectionState_Parse(absl::string_view name, LeAclConnectionState* value);
enum LeConnectionOriginType : int {
  ORIGIN_UNSPECIFIED = 0,
  ORIGIN_NATIVE = 1,
  ORIGIN_JAVA = 2,
};

bool LeConnectionOriginType_IsValid(int value);
extern const uint32_t LeConnectionOriginType_internal_data_[];
constexpr LeConnectionOriginType LeConnectionOriginType_MIN = static_cast<LeConnectionOriginType>(0);
constexpr LeConnectionOriginType LeConnectionOriginType_MAX = static_cast<LeConnectionOriginType>(2);
constexpr int LeConnectionOriginType_ARRAYSIZE = 2 + 1;
const std::string& LeConnectionOriginType_Name(LeConnectionOriginType value);
template <typename T>
const std::string& LeConnectionOriginType_Name(T value) {
  static_assert(std::is_same<T, LeConnectionOriginType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeConnectionOriginType_Name().");
  return LeConnectionOriginType_Name(static_cast<LeConnectionOriginType>(value));
}
const std::string& LeConnectionOriginType_Name(LeConnectionOriginType value);
bool LeConnectionOriginType_Parse(absl::string_view name, LeConnectionOriginType* value);
enum LeConnectionType : int {
  CONNECTION_TYPE_UNSPECIFIED = 0,
  CONNECTION_TYPE_LE_ACL = 1,
  CONNECTION_TYPE_GATT = 2,
  CONNECTION_TYPE_L2CAP_FIXED_CHNL_SMP = 3,
  CONNECTION_TYPE_L2CAP_FIXED_CHNL_ATT = 4,
  CONNECTION_TYPE_L2CAP_FIXED_CHNL_LE_SIGNALLING = 5,
  CONNECTION_TYPE_L2CAP_FIXED_CHNL_AMP = 6,
  CONNECTION_TYPE_L2CAP_FIXED_CHNL_SMP_BR_EDR = 7,
};

bool LeConnectionType_IsValid(int value);
extern const uint32_t LeConnectionType_internal_data_[];
constexpr LeConnectionType LeConnectionType_MIN = static_cast<LeConnectionType>(0);
constexpr LeConnectionType LeConnectionType_MAX = static_cast<LeConnectionType>(7);
constexpr int LeConnectionType_ARRAYSIZE = 7 + 1;
const std::string& LeConnectionType_Name(LeConnectionType value);
template <typename T>
const std::string& LeConnectionType_Name(T value) {
  static_assert(std::is_same<T, LeConnectionType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeConnectionType_Name().");
  return LeConnectionType_Name(static_cast<LeConnectionType>(value));
}
const std::string& LeConnectionType_Name(LeConnectionType value);
bool LeConnectionType_Parse(absl::string_view name, LeConnectionType* value);
enum LeConnectionState : int {
  STATE_UNSPECIFIED = 0,
  STATE_LE_ACL_START = 1,
  STATE_LE_ACL_END = 2,
  STATE_LE_ACL_CANCEL = 3,
  STATE_LE_ACL_TIMEOUT = 4,
  STATE_GATT_APP_USE_LINK_FLAG = 5,
  STATE_GATT_CREATE_DIRECT_CONN = 6,
  STATE_GATT_HOLD_LINK_EMPTY = 7,
  STATE_GATT_CONNECT_NATIVE = 8,
  STATE_GATT_APP_CREATE_LE_ACL = 9,
  STATE_GATT_CONN_STATE_CHANGE_CLIENT = 10,
  STATE_GATT_CONN_STATE_CHANGE_SERVER = 11,
  STATE_L2CAP_FIXED_CHNL_START_CREATE_CONN = 12,
  STATE_L2CAP_FIXED_CHNL_START_LE_ACL = 13,
  STATE_L2CAP_FIXED_CHNL_LE_ACL_FINISH = 14,
};

bool LeConnectionState_IsValid(int value);
extern const uint32_t LeConnectionState_internal_data_[];
constexpr LeConnectionState LeConnectionState_MIN = static_cast<LeConnectionState>(0);
constexpr LeConnectionState LeConnectionState_MAX = static_cast<LeConnectionState>(14);
constexpr int LeConnectionState_ARRAYSIZE = 14 + 1;
const std::string& LeConnectionState_Name(LeConnectionState value);
template <typename T>
const std::string& LeConnectionState_Name(T value) {
  static_assert(std::is_same<T, LeConnectionState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeConnectionState_Name().");
  return LeConnectionState_Name(static_cast<LeConnectionState>(value));
}
const std::string& LeConnectionState_Name(LeConnectionState value);
bool LeConnectionState_Parse(absl::string_view name, LeConnectionState* value);
enum LeScanCallbackType : int {
  TYPE_UNKNOWN = 0,
  TYPE_ALL_MATCHES = 1,
  TYPE_FIRST_MATCH = 2,
  TYPE_MATCH_LOST = 4,
  TYPE_ALL_MATCHES_AUTO_BATCH = 8,
};

bool LeScanCallbackType_IsValid(int value);
extern const uint32_t LeScanCallbackType_internal_data_[];
constexpr LeScanCallbackType LeScanCallbackType_MIN = static_cast<LeScanCallbackType>(0);
constexpr LeScanCallbackType LeScanCallbackType_MAX = static_cast<LeScanCallbackType>(8);
constexpr int LeScanCallbackType_ARRAYSIZE = 8 + 1;
const std::string& LeScanCallbackType_Name(LeScanCallbackType value);
template <typename T>
const std::string& LeScanCallbackType_Name(T value) {
  static_assert(std::is_same<T, LeScanCallbackType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeScanCallbackType_Name().");
  return LeScanCallbackType_Name(static_cast<LeScanCallbackType>(value));
}
const std::string& LeScanCallbackType_Name(LeScanCallbackType value);
bool LeScanCallbackType_Parse(absl::string_view name, LeScanCallbackType* value);
enum LeScanType : int {
  SCAN_TYPE_UNKNOWN = 0,
  SCAN_TYPE_REGULAR = 1,
  SCAN_TYPE_BATCH = 2,
  SCAN_TYPE_AUTO_BATCH = 3,
};

bool LeScanType_IsValid(int value);
extern const uint32_t LeScanType_internal_data_[];
constexpr LeScanType LeScanType_MIN = static_cast<LeScanType>(0);
constexpr LeScanType LeScanType_MAX = static_cast<LeScanType>(3);
constexpr int LeScanType_ARRAYSIZE = 3 + 1;
const std::string& LeScanType_Name(LeScanType value);
template <typename T>
const std::string& LeScanType_Name(T value) {
  static_assert(std::is_same<T, LeScanType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeScanType_Name().");
  return LeScanType_Name(static_cast<LeScanType>(value));
}
const std::string& LeScanType_Name(LeScanType value);
bool LeScanType_Parse(absl::string_view name, LeScanType* value);
enum LeScanMode : int {
  SCAN_MODE_UNKNOWN = 0,
  SCAN_MODE_OPPORTUNISTIC = 1,
  SCAN_MODE_LOW_POWER = 2,
  SCAN_MODE_BALANCED = 3,
  SCAN_MODE_LOW_LATENCY = 4,
  SCAN_MODE_AMBIENT_DISCOVERY = 5,
  SCAN_MODE_SCREEN_OFF = 6,
  SCAN_MODE_SCREEN_OFF_BALANCED = 7,
  SCAN_MODE_CUSTOM = 20,
};

bool LeScanMode_IsValid(int value);
extern const uint32_t LeScanMode_internal_data_[];
constexpr LeScanMode LeScanMode_MIN = static_cast<LeScanMode>(0);
constexpr LeScanMode LeScanMode_MAX = static_cast<LeScanMode>(20);
constexpr int LeScanMode_ARRAYSIZE = 20 + 1;
const std::string& LeScanMode_Name(LeScanMode value);
template <typename T>
const std::string& LeScanMode_Name(T value) {
  static_assert(std::is_same<T, LeScanMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeScanMode_Name().");
  return LeScanMode_Name(static_cast<LeScanMode>(value));
}
const std::string& LeScanMode_Name(LeScanMode value);
bool LeScanMode_Parse(absl::string_view name, LeScanMode* value);
enum LeScanAbuseReason : int {
  REASON_UNKNOWN = 0,
  REASON_SCAN_TIMEOUT = 1,
  REASON_HW_FILTER_NA = 2,
  REASON_TRACKING_HW_FILTER_NA = 3,
};

bool LeScanAbuseReason_IsValid(int value);
extern const uint32_t LeScanAbuseReason_internal_data_[];
constexpr LeScanAbuseReason LeScanAbuseReason_MIN = static_cast<LeScanAbuseReason>(0);
constexpr LeScanAbuseReason LeScanAbuseReason_MAX = static_cast<LeScanAbuseReason>(3);
constexpr int LeScanAbuseReason_ARRAYSIZE = 3 + 1;
const std::string& LeScanAbuseReason_Name(LeScanAbuseReason value);
template <typename T>
const std::string& LeScanAbuseReason_Name(T value) {
  static_assert(std::is_same<T, LeScanAbuseReason>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeScanAbuseReason_Name().");
  return LeScanAbuseReason_Name(static_cast<LeScanAbuseReason>(value));
}
const std::string& LeScanAbuseReason_Name(LeScanAbuseReason value);
bool LeScanAbuseReason_Parse(absl::string_view name, LeScanAbuseReason* value);
enum LeAdvInterval : int {
  INTERVAL_UNKNOWN = 0,
  INTERVAL_HIGH = 1,
  INTERVAL_MEDIUM = 2,
  INTERVAL_LOW = 3,
};

bool LeAdvInterval_IsValid(int value);
extern const uint32_t LeAdvInterval_internal_data_[];
constexpr LeAdvInterval LeAdvInterval_MIN = static_cast<LeAdvInterval>(0);
constexpr LeAdvInterval LeAdvInterval_MAX = static_cast<LeAdvInterval>(3);
constexpr int LeAdvInterval_ARRAYSIZE = 3 + 1;
const std::string& LeAdvInterval_Name(LeAdvInterval value);
template <typename T>
const std::string& LeAdvInterval_Name(T value) {
  static_assert(std::is_same<T, LeAdvInterval>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeAdvInterval_Name().");
  return LeAdvInterval_Name(static_cast<LeAdvInterval>(value));
}
const std::string& LeAdvInterval_Name(LeAdvInterval value);
bool LeAdvInterval_Parse(absl::string_view name, LeAdvInterval* value);
enum LeAdvTxPower : int {
  TX_POWER_UNKNOWN = 0,
  TX_POWER_ULTRA_LOW = 1,
  TX_POWER_LOW = 2,
  TX_POWER_MEDIUM = 3,
  TX_POWER_HIGH = 4,
};

bool LeAdvTxPower_IsValid(int value);
extern const uint32_t LeAdvTxPower_internal_data_[];
constexpr LeAdvTxPower LeAdvTxPower_MIN = static_cast<LeAdvTxPower>(0);
constexpr LeAdvTxPower LeAdvTxPower_MAX = static_cast<LeAdvTxPower>(4);
constexpr int LeAdvTxPower_ARRAYSIZE = 4 + 1;
const std::string& LeAdvTxPower_Name(LeAdvTxPower value);
template <typename T>
const std::string& LeAdvTxPower_Name(T value) {
  static_assert(std::is_same<T, LeAdvTxPower>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeAdvTxPower_Name().");
  return LeAdvTxPower_Name(static_cast<LeAdvTxPower>(value));
}
const std::string& LeAdvTxPower_Name(LeAdvTxPower value);
bool LeAdvTxPower_Parse(absl::string_view name, LeAdvTxPower* value);
enum LeAdvOpCode : int {
  ERROR_CODE_UNKNOWN = 0,
  ERROR_CODE_ON_START = 1,
};

bool LeAdvOpCode_IsValid(int value);
extern const uint32_t LeAdvOpCode_internal_data_[];
constexpr LeAdvOpCode LeAdvOpCode_MIN = static_cast<LeAdvOpCode>(0);
constexpr LeAdvOpCode LeAdvOpCode_MAX = static_cast<LeAdvOpCode>(1);
constexpr int LeAdvOpCode_ARRAYSIZE = 1 + 1;
const std::string& LeAdvOpCode_Name(LeAdvOpCode value);
template <typename T>
const std::string& LeAdvOpCode_Name(T value) {
  static_assert(std::is_same<T, LeAdvOpCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeAdvOpCode_Name().");
  return LeAdvOpCode_Name(static_cast<LeAdvOpCode>(value));
}
const std::string& LeAdvOpCode_Name(LeAdvOpCode value);
bool LeAdvOpCode_Parse(absl::string_view name, LeAdvOpCode* value);
enum LeAdvStatusCode : int {
  ADV_STATUS_UNKNOWN = 0,
  ADV_STATUS_SUCCESS = 1,
  ADV_STATUS_FAILED_DATA_TOO_LARGE = 2,
  ADV_STATUS_FAILED_TOO_MANY_ADVERTISERS = 3,
  ADV_STATUS_FAILED_ALREADY_STARTED = 4,
  ADV_STATUS_FAILED_INTERNAL_ERROR = 5,
  ADV_STATUS_FAILED_FEATURE_UNSUPPORTED = 6,
};

bool LeAdvStatusCode_IsValid(int value);
extern const uint32_t LeAdvStatusCode_internal_data_[];
constexpr LeAdvStatusCode LeAdvStatusCode_MIN = static_cast<LeAdvStatusCode>(0);
constexpr LeAdvStatusCode LeAdvStatusCode_MAX = static_cast<LeAdvStatusCode>(6);
constexpr int LeAdvStatusCode_ARRAYSIZE = 6 + 1;
const std::string& LeAdvStatusCode_Name(LeAdvStatusCode value);
template <typename T>
const std::string& LeAdvStatusCode_Name(T value) {
  static_assert(std::is_same<T, LeAdvStatusCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LeAdvStatusCode_Name().");
  return LeAdvStatusCode_Name(static_cast<LeAdvStatusCode>(value));
}
const std::string& LeAdvStatusCode_Name(LeAdvStatusCode value);
bool LeAdvStatusCode_Parse(absl::string_view name, LeAdvStatusCode* value);
enum AppImportance : int {
  IMPORTANCE_UNKNOWN = 0,
  IMPORTANCE_LOWER_THAN_FGS = 1,
  IMPORTANCE_EQUAL_TO_FGS = 2,
  IMPORTANCE_HIGHER_THAN_FGS = 3,
};

bool AppImportance_IsValid(int value);
extern const uint32_t AppImportance_internal_data_[];
constexpr AppImportance AppImportance_MIN = static_cast<AppImportance>(0);
constexpr AppImportance AppImportance_MAX = static_cast<AppImportance>(3);
constexpr int AppImportance_ARRAYSIZE = 3 + 1;
const std::string& AppImportance_Name(AppImportance value);
template <typename T>
const std::string& AppImportance_Name(T value) {
  static_assert(std::is_same<T, AppImportance>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AppImportance_Name().");
  return AppImportance_Name(static_cast<AppImportance>(value));
}
const std::string& AppImportance_Name(AppImportance value);
bool AppImportance_Parse(absl::string_view name, AppImportance* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace le
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::le::LeAclConnectionState> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeConnectionOriginType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeConnectionType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeConnectionState> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeScanCallbackType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeScanType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeScanMode> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeScanAbuseReason> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeAdvInterval> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeAdvTxPower> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeAdvOpCode> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::LeAdvStatusCode> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::le::AppImportance> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fle_2fenums_2eproto_2epb_2eh
