// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/leaudio/enums.proto

#include "frameworks/proto_logging/stats/enums/bluetooth/leaudio/enums.pb.h"

#include <algorithm>
#include <cstdint>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace android {
namespace bluetooth {
namespace leaudio {
}  // namespace leaudio
}  // namespace bluetooth
}  // namespace android
namespace android {
namespace bluetooth {
namespace leaudio {
PROTOBUF_CONSTINIT const uint32_t ContextType_internal_data_[] = {
    851968u, 0u, };
bool ContextType_IsValid(int value) {
  return 0 <= value && value <= 12;
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    ContextType_strings[13] = {};

static const char ContextType_names[] = {
    "CONTEXT_TYPE_ATTENTION_SEEKING"
    "CONTEXT_TYPE_COMMUNICATION"
    "CONTEXT_TYPE_EMERGENCY_ALERT"
    "CONTEXT_TYPE_GAME"
    "CONTEXT_TYPE_IMMEDIATE_ALERT"
    "CONTEXT_TYPE_INSTRUCTIONAL"
    "CONTEXT_TYPE_INVALID"
    "CONTEXT_TYPE_LIVE"
    "CONTEXT_TYPE_MAN_MACHINE"
    "CONTEXT_TYPE_MEDIA"
    "CONTEXT_TYPE_RINGTONE"
    "CONTEXT_TYPE_TV"
    "CONTEXT_TYPE_UNSPECIFIED"
};

static const ::google::protobuf::internal::EnumEntry ContextType_entries[] =
    {
        {{&ContextType_names[0], 30}, 5},
        {{&ContextType_names[30], 26}, 2},
        {{&ContextType_names[56], 28}, 8},
        {{&ContextType_names[84], 17}, 12},
        {{&ContextType_names[101], 28}, 6},
        {{&ContextType_names[129], 26}, 4},
        {{&ContextType_names[155], 20}, 0},
        {{&ContextType_names[175], 17}, 11},
        {{&ContextType_names[192], 24}, 7},
        {{&ContextType_names[216], 18}, 3},
        {{&ContextType_names[234], 21}, 9},
        {{&ContextType_names[255], 15}, 10},
        {{&ContextType_names[270], 24}, 1},
};

static const int ContextType_entries_by_number[] = {
    6,  // 0 -> CONTEXT_TYPE_INVALID
    12,  // 1 -> CONTEXT_TYPE_UNSPECIFIED
    1,  // 2 -> CONTEXT_TYPE_COMMUNICATION
    9,  // 3 -> CONTEXT_TYPE_MEDIA
    5,  // 4 -> CONTEXT_TYPE_INSTRUCTIONAL
    0,  // 5 -> CONTEXT_TYPE_ATTENTION_SEEKING
    4,  // 6 -> CONTEXT_TYPE_IMMEDIATE_ALERT
    8,  // 7 -> CONTEXT_TYPE_MAN_MACHINE
    2,  // 8 -> CONTEXT_TYPE_EMERGENCY_ALERT
    10,  // 9 -> CONTEXT_TYPE_RINGTONE
    11,  // 10 -> CONTEXT_TYPE_TV
    7,  // 11 -> CONTEXT_TYPE_LIVE
    3,  // 12 -> CONTEXT_TYPE_GAME
};

const std::string& ContextType_Name(ContextType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          ContextType_entries, ContextType_entries_by_number,
          13, ContextType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      ContextType_entries, ContextType_entries_by_number, 13,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : ContextType_strings[idx].get();
}

bool ContextType_Parse(absl::string_view name, ContextType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      ContextType_entries, 13, name, &int_value);
  if (success) {
    *value = static_cast<ContextType>(int_value);
  }
  return success;
}
PROTOBUF_CONSTINIT const uint32_t ConnectionStatus_internal_data_[] = {
    3014656u, 96u, 0u, 4290772992u, 131071u, };
bool ConnectionStatus_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ConnectionStatus_internal_data_);
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    ConnectionStatus_strings[73] = {};

static const char ConnectionStatus_names[] = {
    "CONNECTION_STATUS_FAILED"
    "CONNECTION_STATUS_FAILED_BTM_BAD_VALUE_RET"
    "CONNECTION_STATUS_FAILED_BTM_BUSY"
    "CONNECTION_STATUS_FAILED_BTM_CMD_STARTED"
    "CONNECTION_STATUS_FAILED_BTM_CMD_STORED"
    "CONNECTION_STATUS_FAILED_BTM_DELAY_CHECK"
    "CONNECTION_STATUS_FAILED_BTM_DEVICE_TIMEOUT"
    "CONNECTION_STATUS_FAILED_BTM_DEV_RESET"
    "CONNECTION_STATUS_FAILED_BTM_DEV_RESTRICT_LISTED"
    "CONNECTION_STATUS_FAILED_BTM_ERR_KEY_MISSING"
    "CONNECTION_STATUS_FAILED_BTM_ERR_PROCESSING"
    "CONNECTION_STATUS_FAILED_BTM_FAILED_ON_SECURITY"
    "CONNECTION_STATUS_FAILED_BTM_ILLEGAL_ACTION"
    "CONNECTION_STATUS_FAILED_BTM_ILLEGAL_VALUE"
    "CONNECTION_STATUS_FAILED_BTM_INSUFFICIENT_ENCRYPT_KEY_SIZE"
    "CONNECTION_STATUS_FAILED_BTM_MAX_STATUS_VALUE"
    "CONNECTION_STATUS_FAILED_BTM_MODE4_LEVEL4_NOT_SUPPORTED"
    "CONNECTION_STATUS_FAILED_BTM_MODE_UNSUPPORTED"
    "CONNECTION_STATUS_FAILED_BTM_NOT_AUTHENTICATED"
    "CONNECTION_STATUS_FAILED_BTM_NOT_AUTHORIZED"
    "CONNECTION_STATUS_FAILED_BTM_NOT_ENCRYPTED"
    "CONNECTION_STATUS_FAILED_BTM_NO_RESOURCES"
    "CONNECTION_STATUS_FAILED_BTM_REPEATED_ATTEMPTS"
    "CONNECTION_STATUS_FAILED_BTM_SCO_BAD_LENGTH"
    "CONNECTION_STATUS_FAILED_BTM_SUCCESS_NO_SECURITY"
    "CONNECTION_STATUS_FAILED_BTM_UNDEFINED"
    "CONNECTION_STATUS_FAILED_BTM_UNKNOWN_ADDR"
    "CONNECTION_STATUS_FAILED_BTM_WRONG_MODE"
    "CONNECTION_STATUS_FAILED_CONNECT_DISABLING_GROUP"
    "CONNECTION_STATUS_FAILED_CONNECT_UNBONDED_DEV"
    "CONNECTION_STATUS_FAILED_GATT_ALREADY_OPEN"
    "CONNECTION_STATUS_FAILED_GATT_AUTH_FAIL"
    "CONNECTION_STATUS_FAILED_GATT_BUSY"
    "CONNECTION_STATUS_FAILED_GATT_CANCEL"
    "CONNECTION_STATUS_FAILED_GATT_CCC_CFG_ERR"
    "CONNECTION_STATUS_FAILED_GATT_CMD_STARTED"
    "CONNECTION_STATUS_FAILED_GATT_CONGESTED"
    "CONNECTION_STATUS_FAILED_GATT_CONNECTION_TIMEOUT"
    "CONNECTION_STATUS_FAILED_GATT_DATABASE_OUT_OF_SYNC"
    "CONNECTION_STATUS_FAILED_GATT_DB_FULL"
    "CONNECTION_STATUS_FAILED_GATT_DUP_REG"
    "CONNECTION_STATUS_FAILED_GATT_ENCRYPED_NO_MITM"
    "CONNECTION_STATUS_FAILED_GATT_ERROR"
    "CONNECTION_STATUS_FAILED_GATT_ERR_UNLIKELY"
    "CONNECTION_STATUS_FAILED_GATT_ILLEGAL_PARAMETER"
    "CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHENTICATION"
    "CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHORIZATION"
    "CONNECTION_STATUS_FAILED_GATT_INSUF_ENCRYPTION"
    "CONNECTION_STATUS_FAILED_GATT_INSUF_KEY_SIZE"
    "CONNECTION_STATUS_FAILED_GATT_INSUF_RESOURCE"
    "CONNECTION_STATUS_FAILED_GATT_INTERNAL_ERROR"
    "CONNECTION_STATUS_FAILED_GATT_INVALID_ATTR_LEN"
    "CONNECTION_STATUS_FAILED_GATT_INVALID_CFG"
    "CONNECTION_STATUS_FAILED_GATT_INVALID_HANDLE"
    "CONNECTION_STATUS_FAILED_GATT_INVALID_OFFSET"
    "CONNECTION_STATUS_FAILED_GATT_INVALID_PDU"
    "CONNECTION_STATUS_FAILED_GATT_NOT_ENCRYPTED"
    "CONNECTION_STATUS_FAILED_GATT_NOT_FOUND"
    "CONNECTION_STATUS_FAILED_GATT_NOT_LONG"
    "CONNECTION_STATUS_FAILED_GATT_NO_RESOURCES"
    "CONNECTION_STATUS_FAILED_GATT_OUT_OF_RANGE"
    "CONNECTION_STATUS_FAILED_GATT_PENDING"
    "CONNECTION_STATUS_FAILED_GATT_PRC_IN_PROGRESS"
    "CONNECTION_STATUS_FAILED_GATT_PREPARE_Q_FULL"
    "CONNECTION_STATUS_FAILED_GATT_READ_NOT_PERMIT"
    "CONNECTION_STATUS_FAILED_GATT_REQ_NOT_SUPPORTED"
    "CONNECTION_STATUS_FAILED_GATT_SERVICE_STARTED"
    "CONNECTION_STATUS_FAILED_GATT_UNSUPPORT_GRP_TYPE"
    "CONNECTION_STATUS_FAILED_GATT_VALUE_NOT_ALLOWED"
    "CONNECTION_STATUS_FAILED_GATT_WRITE_NOT_PERMIT"
    "CONNECTION_STATUS_FAILED_GATT_WRONG_STATE"
    "CONNECTION_STATUS_SUCCESS"
    "CONNECTION_STATUS_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry ConnectionStatus_entries[] =
    {
        {{&ConnectionStatus_names[0], 24}, 2},
        {{&ConnectionStatus_names[24], 42}, 108},
        {{&ConnectionStatus_names[66], 33}, 101},
        {{&ConnectionStatus_names[99], 40}, 100},
        {{&ConnectionStatus_names[139], 39}, 112},
        {{&ConnectionStatus_names[178], 40}, 114},
        {{&ConnectionStatus_names[218], 43}, 107},
        {{&ConnectionStatus_names[261], 38}, 111},
        {{&ConnectionStatus_names[299], 48}, 120},
        {{&ConnectionStatus_names[347], 44}, 121},
        {{&ConnectionStatus_names[391], 43}, 109},
        {{&ConnectionStatus_names[434], 47}, 117},
        {{&ConnectionStatus_names[481], 43}, 113},
        {{&ConnectionStatus_names[524], 42}, 104},
        {{&ConnectionStatus_names[566], 58}, 124},
        {{&ConnectionStatus_names[624], 45}, 125},
        {{&ConnectionStatus_names[669], 55}, 119},
        {{&ConnectionStatus_names[724], 45}, 103},
        {{&ConnectionStatus_names[769], 46}, 122},
        {{&ConnectionStatus_names[815], 43}, 110},
        {{&ConnectionStatus_names[858], 42}, 123},
        {{&ConnectionStatus_names[900], 41}, 102},
        {{&ConnectionStatus_names[941], 46}, 118},
        {{&ConnectionStatus_names[987], 43}, 115},
        {{&ConnectionStatus_names[1030], 48}, 116},
        {{&ConnectionStatus_names[1078], 38}, 126},
        {{&ConnectionStatus_names[1116], 41}, 106},
        {{&ConnectionStatus_names[1157], 39}, 105},
        {{&ConnectionStatus_names[1196], 48}, 4},
        {{&ConnectionStatus_names[1244], 45}, 3},
        {{&ConnectionStatus_names[1289], 42}, 40},
        {{&ConnectionStatus_names[1331], 39}, 33},
        {{&ConnectionStatus_names[1370], 34}, 29},
        {{&ConnectionStatus_names[1404], 36}, 41},
        {{&ConnectionStatus_names[1440], 41}, 43},
        {{&ConnectionStatus_names[1481], 41}, 31},
        {{&ConnectionStatus_names[1522], 39}, 38},
        {{&ConnectionStatus_names[1561], 48}, 42},
        {{&ConnectionStatus_names[1609], 50}, 22},
        {{&ConnectionStatus_names[1659], 37}, 28},
        {{&ConnectionStatus_names[1696], 37}, 39},
        {{&ConnectionStatus_names[1733], 46}, 36},
        {{&ConnectionStatus_names[1779], 35}, 30},
        {{&ConnectionStatus_names[1814], 42}, 18},
        {{&ConnectionStatus_names[1856], 47}, 24},
        {{&ConnectionStatus_names[1903], 50}, 9},
        {{&ConnectionStatus_names[1953], 49}, 12},
        {{&ConnectionStatus_names[2002], 46}, 19},
        {{&ConnectionStatus_names[2048], 44}, 16},
        {{&ConnectionStatus_names[2092], 44}, 21},
        {{&ConnectionStatus_names[2136], 44}, 26},
        {{&ConnectionStatus_names[2180], 46}, 17},
        {{&ConnectionStatus_names[2226], 41}, 34},
        {{&ConnectionStatus_names[2267], 44}, 5},
        {{&ConnectionStatus_names[2311], 44}, 11},
        {{&ConnectionStatus_names[2355], 41}, 8},
        {{&ConnectionStatus_names[2396], 43}, 37},
        {{&ConnectionStatus_names[2439], 39}, 14},
        {{&ConnectionStatus_names[2478], 38}, 15},
        {{&ConnectionStatus_names[2516], 42}, 25},
        {{&ConnectionStatus_names[2558], 42}, 45},
        {{&ConnectionStatus_names[2600], 37}, 32},
        {{&ConnectionStatus_names[2637], 45}, 44},
        {{&ConnectionStatus_names[2682], 44}, 13},
        {{&ConnectionStatus_names[2726], 45}, 6},
        {{&ConnectionStatus_names[2771], 47}, 10},
        {{&ConnectionStatus_names[2818], 45}, 35},
        {{&ConnectionStatus_names[2863], 48}, 20},
        {{&ConnectionStatus_names[2911], 47}, 23},
        {{&ConnectionStatus_names[2958], 46}, 7},
        {{&ConnectionStatus_names[3004], 41}, 27},
        {{&ConnectionStatus_names[3045], 25}, 1},
        {{&ConnectionStatus_names[3070], 25}, 0},
};

static const int ConnectionStatus_entries_by_number[] = {
    72,  // 0 -> CONNECTION_STATUS_UNKNOWN
    71,  // 1 -> CONNECTION_STATUS_SUCCESS
    0,  // 2 -> CONNECTION_STATUS_FAILED
    29,  // 3 -> CONNECTION_STATUS_FAILED_CONNECT_UNBONDED_DEV
    28,  // 4 -> CONNECTION_STATUS_FAILED_CONNECT_DISABLING_GROUP
    53,  // 5 -> CONNECTION_STATUS_FAILED_GATT_INVALID_HANDLE
    64,  // 6 -> CONNECTION_STATUS_FAILED_GATT_READ_NOT_PERMIT
    69,  // 7 -> CONNECTION_STATUS_FAILED_GATT_WRITE_NOT_PERMIT
    55,  // 8 -> CONNECTION_STATUS_FAILED_GATT_INVALID_PDU
    45,  // 9 -> CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHENTICATION
    65,  // 10 -> CONNECTION_STATUS_FAILED_GATT_REQ_NOT_SUPPORTED
    54,  // 11 -> CONNECTION_STATUS_FAILED_GATT_INVALID_OFFSET
    46,  // 12 -> CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHORIZATION
    63,  // 13 -> CONNECTION_STATUS_FAILED_GATT_PREPARE_Q_FULL
    57,  // 14 -> CONNECTION_STATUS_FAILED_GATT_NOT_FOUND
    58,  // 15 -> CONNECTION_STATUS_FAILED_GATT_NOT_LONG
    48,  // 16 -> CONNECTION_STATUS_FAILED_GATT_INSUF_KEY_SIZE
    51,  // 17 -> CONNECTION_STATUS_FAILED_GATT_INVALID_ATTR_LEN
    43,  // 18 -> CONNECTION_STATUS_FAILED_GATT_ERR_UNLIKELY
    47,  // 19 -> CONNECTION_STATUS_FAILED_GATT_INSUF_ENCRYPTION
    67,  // 20 -> CONNECTION_STATUS_FAILED_GATT_UNSUPPORT_GRP_TYPE
    49,  // 21 -> CONNECTION_STATUS_FAILED_GATT_INSUF_RESOURCE
    38,  // 22 -> CONNECTION_STATUS_FAILED_GATT_DATABASE_OUT_OF_SYNC
    68,  // 23 -> CONNECTION_STATUS_FAILED_GATT_VALUE_NOT_ALLOWED
    44,  // 24 -> CONNECTION_STATUS_FAILED_GATT_ILLEGAL_PARAMETER
    59,  // 25 -> CONNECTION_STATUS_FAILED_GATT_NO_RESOURCES
    50,  // 26 -> CONNECTION_STATUS_FAILED_GATT_INTERNAL_ERROR
    70,  // 27 -> CONNECTION_STATUS_FAILED_GATT_WRONG_STATE
    39,  // 28 -> CONNECTION_STATUS_FAILED_GATT_DB_FULL
    32,  // 29 -> CONNECTION_STATUS_FAILED_GATT_BUSY
    42,  // 30 -> CONNECTION_STATUS_FAILED_GATT_ERROR
    35,  // 31 -> CONNECTION_STATUS_FAILED_GATT_CMD_STARTED
    61,  // 32 -> CONNECTION_STATUS_FAILED_GATT_PENDING
    31,  // 33 -> CONNECTION_STATUS_FAILED_GATT_AUTH_FAIL
    52,  // 34 -> CONNECTION_STATUS_FAILED_GATT_INVALID_CFG
    66,  // 35 -> CONNECTION_STATUS_FAILED_GATT_SERVICE_STARTED
    41,  // 36 -> CONNECTION_STATUS_FAILED_GATT_ENCRYPED_NO_MITM
    56,  // 37 -> CONNECTION_STATUS_FAILED_GATT_NOT_ENCRYPTED
    36,  // 38 -> CONNECTION_STATUS_FAILED_GATT_CONGESTED
    40,  // 39 -> CONNECTION_STATUS_FAILED_GATT_DUP_REG
    30,  // 40 -> CONNECTION_STATUS_FAILED_GATT_ALREADY_OPEN
    33,  // 41 -> CONNECTION_STATUS_FAILED_GATT_CANCEL
    37,  // 42 -> CONNECTION_STATUS_FAILED_GATT_CONNECTION_TIMEOUT
    34,  // 43 -> CONNECTION_STATUS_FAILED_GATT_CCC_CFG_ERR
    62,  // 44 -> CONNECTION_STATUS_FAILED_GATT_PRC_IN_PROGRESS
    60,  // 45 -> CONNECTION_STATUS_FAILED_GATT_OUT_OF_RANGE
    3,  // 100 -> CONNECTION_STATUS_FAILED_BTM_CMD_STARTED
    2,  // 101 -> CONNECTION_STATUS_FAILED_BTM_BUSY
    21,  // 102 -> CONNECTION_STATUS_FAILED_BTM_NO_RESOURCES
    17,  // 103 -> CONNECTION_STATUS_FAILED_BTM_MODE_UNSUPPORTED
    13,  // 104 -> CONNECTION_STATUS_FAILED_BTM_ILLEGAL_VALUE
    27,  // 105 -> CONNECTION_STATUS_FAILED_BTM_WRONG_MODE
    26,  // 106 -> CONNECTION_STATUS_FAILED_BTM_UNKNOWN_ADDR
    6,  // 107 -> CONNECTION_STATUS_FAILED_BTM_DEVICE_TIMEOUT
    1,  // 108 -> CONNECTION_STATUS_FAILED_BTM_BAD_VALUE_RET
    10,  // 109 -> CONNECTION_STATUS_FAILED_BTM_ERR_PROCESSING
    19,  // 110 -> CONNECTION_STATUS_FAILED_BTM_NOT_AUTHORIZED
    7,  // 111 -> CONNECTION_STATUS_FAILED_BTM_DEV_RESET
    4,  // 112 -> CONNECTION_STATUS_FAILED_BTM_CMD_STORED
    12,  // 113 -> CONNECTION_STATUS_FAILED_BTM_ILLEGAL_ACTION
    5,  // 114 -> CONNECTION_STATUS_FAILED_BTM_DELAY_CHECK
    23,  // 115 -> CONNECTION_STATUS_FAILED_BTM_SCO_BAD_LENGTH
    24,  // 116 -> CONNECTION_STATUS_FAILED_BTM_SUCCESS_NO_SECURITY
    11,  // 117 -> CONNECTION_STATUS_FAILED_BTM_FAILED_ON_SECURITY
    22,  // 118 -> CONNECTION_STATUS_FAILED_BTM_REPEATED_ATTEMPTS
    16,  // 119 -> CONNECTION_STATUS_FAILED_BTM_MODE4_LEVEL4_NOT_SUPPORTED
    8,  // 120 -> CONNECTION_STATUS_FAILED_BTM_DEV_RESTRICT_LISTED
    9,  // 121 -> CONNECTION_STATUS_FAILED_BTM_ERR_KEY_MISSING
    18,  // 122 -> CONNECTION_STATUS_FAILED_BTM_NOT_AUTHENTICATED
    20,  // 123 -> CONNECTION_STATUS_FAILED_BTM_NOT_ENCRYPTED
    14,  // 124 -> CONNECTION_STATUS_FAILED_BTM_INSUFFICIENT_ENCRYPT_KEY_SIZE
    15,  // 125 -> CONNECTION_STATUS_FAILED_BTM_MAX_STATUS_VALUE
    25,  // 126 -> CONNECTION_STATUS_FAILED_BTM_UNDEFINED
};

const std::string& ConnectionStatus_Name(ConnectionStatus value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          ConnectionStatus_entries, ConnectionStatus_entries_by_number,
          73, ConnectionStatus_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      ConnectionStatus_entries, ConnectionStatus_entries_by_number, 73,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : ConnectionStatus_strings[idx].get();
}

bool ConnectionStatus_Parse(absl::string_view name, ConnectionStatus* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      ConnectionStatus_entries, 73, name, &int_value);
  if (success) {
    *value = static_cast<ConnectionStatus>(int_value);
  }
  return success;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace leaudio
}  // namespace bluetooth
}  // namespace android
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
