// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frameworks/proto_logging/stats/enums/bluetooth/leaudio/enums.proto
// Protobuf C++ Version: 4.25.8

#ifndef GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fleaudio_2fenums_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fleaudio_2fenums_2eproto_2epb_2eh

#include <cstdint>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025008 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fleaudio_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fleaudio_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace android {
namespace bluetooth {
namespace leaudio {
enum ContextType : int {
  CONTEXT_TYPE_INVALID = 0,
  CONTEXT_TYPE_UNSPECIFIED = 1,
  CONTEXT_TYPE_COMMUNICATION = 2,
  CONTEXT_TYPE_MEDIA = 3,
  CONTEXT_TYPE_INSTRUCTIONAL = 4,
  CONTEXT_TYPE_ATTENTION_SEEKING = 5,
  CONTEXT_TYPE_IMMEDIATE_ALERT = 6,
  CONTEXT_TYPE_MAN_MACHINE = 7,
  CONTEXT_TYPE_EMERGENCY_ALERT = 8,
  CONTEXT_TYPE_RINGTONE = 9,
  CONTEXT_TYPE_TV = 10,
  CONTEXT_TYPE_LIVE = 11,
  CONTEXT_TYPE_GAME = 12,
};

bool ContextType_IsValid(int value);
extern const uint32_t ContextType_internal_data_[];
constexpr ContextType ContextType_MIN = static_cast<ContextType>(0);
constexpr ContextType ContextType_MAX = static_cast<ContextType>(12);
constexpr int ContextType_ARRAYSIZE = 12 + 1;
const std::string& ContextType_Name(ContextType value);
template <typename T>
const std::string& ContextType_Name(T value) {
  static_assert(std::is_same<T, ContextType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ContextType_Name().");
  return ContextType_Name(static_cast<ContextType>(value));
}
const std::string& ContextType_Name(ContextType value);
bool ContextType_Parse(absl::string_view name, ContextType* value);
enum ConnectionStatus : int {
  CONNECTION_STATUS_UNKNOWN = 0,
  CONNECTION_STATUS_SUCCESS = 1,
  CONNECTION_STATUS_FAILED = 2,
  CONNECTION_STATUS_FAILED_CONNECT_UNBONDED_DEV = 3,
  CONNECTION_STATUS_FAILED_CONNECT_DISABLING_GROUP = 4,
  CONNECTION_STATUS_FAILED_GATT_INVALID_HANDLE = 5,
  CONNECTION_STATUS_FAILED_GATT_READ_NOT_PERMIT = 6,
  CONNECTION_STATUS_FAILED_GATT_WRITE_NOT_PERMIT = 7,
  CONNECTION_STATUS_FAILED_GATT_INVALID_PDU = 8,
  CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHENTICATION = 9,
  CONNECTION_STATUS_FAILED_GATT_REQ_NOT_SUPPORTED = 10,
  CONNECTION_STATUS_FAILED_GATT_INVALID_OFFSET = 11,
  CONNECTION_STATUS_FAILED_GATT_INSUF_AUTHORIZATION = 12,
  CONNECTION_STATUS_FAILED_GATT_PREPARE_Q_FULL = 13,
  CONNECTION_STATUS_FAILED_GATT_NOT_FOUND = 14,
  CONNECTION_STATUS_FAILED_GATT_NOT_LONG = 15,
  CONNECTION_STATUS_FAILED_GATT_INSUF_KEY_SIZE = 16,
  CONNECTION_STATUS_FAILED_GATT_INVALID_ATTR_LEN = 17,
  CONNECTION_STATUS_FAILED_GATT_ERR_UNLIKELY = 18,
  CONNECTION_STATUS_FAILED_GATT_INSUF_ENCRYPTION = 19,
  CONNECTION_STATUS_FAILED_GATT_UNSUPPORT_GRP_TYPE = 20,
  CONNECTION_STATUS_FAILED_GATT_INSUF_RESOURCE = 21,
  CONNECTION_STATUS_FAILED_GATT_DATABASE_OUT_OF_SYNC = 22,
  CONNECTION_STATUS_FAILED_GATT_VALUE_NOT_ALLOWED = 23,
  CONNECTION_STATUS_FAILED_GATT_ILLEGAL_PARAMETER = 24,
  CONNECTION_STATUS_FAILED_GATT_NO_RESOURCES = 25,
  CONNECTION_STATUS_FAILED_GATT_INTERNAL_ERROR = 26,
  CONNECTION_STATUS_FAILED_GATT_WRONG_STATE = 27,
  CONNECTION_STATUS_FAILED_GATT_DB_FULL = 28,
  CONNECTION_STATUS_FAILED_GATT_BUSY = 29,
  CONNECTION_STATUS_FAILED_GATT_ERROR = 30,
  CONNECTION_STATUS_FAILED_GATT_CMD_STARTED = 31,
  CONNECTION_STATUS_FAILED_GATT_PENDING = 32,
  CONNECTION_STATUS_FAILED_GATT_AUTH_FAIL = 33,
  CONNECTION_STATUS_FAILED_GATT_INVALID_CFG = 34,
  CONNECTION_STATUS_FAILED_GATT_SERVICE_STARTED = 35,
  CONNECTION_STATUS_FAILED_GATT_ENCRYPED_NO_MITM = 36,
  CONNECTION_STATUS_FAILED_GATT_NOT_ENCRYPTED = 37,
  CONNECTION_STATUS_FAILED_GATT_CONGESTED = 38,
  CONNECTION_STATUS_FAILED_GATT_DUP_REG = 39,
  CONNECTION_STATUS_FAILED_GATT_ALREADY_OPEN = 40,
  CONNECTION_STATUS_FAILED_GATT_CANCEL = 41,
  CONNECTION_STATUS_FAILED_GATT_CONNECTION_TIMEOUT = 42,
  CONNECTION_STATUS_FAILED_GATT_CCC_CFG_ERR = 43,
  CONNECTION_STATUS_FAILED_GATT_PRC_IN_PROGRESS = 44,
  CONNECTION_STATUS_FAILED_GATT_OUT_OF_RANGE = 45,
  CONNECTION_STATUS_FAILED_BTM_CMD_STARTED = 100,
  CONNECTION_STATUS_FAILED_BTM_BUSY = 101,
  CONNECTION_STATUS_FAILED_BTM_NO_RESOURCES = 102,
  CONNECTION_STATUS_FAILED_BTM_MODE_UNSUPPORTED = 103,
  CONNECTION_STATUS_FAILED_BTM_ILLEGAL_VALUE = 104,
  CONNECTION_STATUS_FAILED_BTM_WRONG_MODE = 105,
  CONNECTION_STATUS_FAILED_BTM_UNKNOWN_ADDR = 106,
  CONNECTION_STATUS_FAILED_BTM_DEVICE_TIMEOUT = 107,
  CONNECTION_STATUS_FAILED_BTM_BAD_VALUE_RET = 108,
  CONNECTION_STATUS_FAILED_BTM_ERR_PROCESSING = 109,
  CONNECTION_STATUS_FAILED_BTM_NOT_AUTHORIZED = 110,
  CONNECTION_STATUS_FAILED_BTM_DEV_RESET = 111,
  CONNECTION_STATUS_FAILED_BTM_CMD_STORED = 112,
  CONNECTION_STATUS_FAILED_BTM_ILLEGAL_ACTION = 113,
  CONNECTION_STATUS_FAILED_BTM_DELAY_CHECK = 114,
  CONNECTION_STATUS_FAILED_BTM_SCO_BAD_LENGTH = 115,
  CONNECTION_STATUS_FAILED_BTM_SUCCESS_NO_SECURITY = 116,
  CONNECTION_STATUS_FAILED_BTM_FAILED_ON_SECURITY = 117,
  CONNECTION_STATUS_FAILED_BTM_REPEATED_ATTEMPTS = 118,
  CONNECTION_STATUS_FAILED_BTM_MODE4_LEVEL4_NOT_SUPPORTED = 119,
  CONNECTION_STATUS_FAILED_BTM_DEV_RESTRICT_LISTED = 120,
  CONNECTION_STATUS_FAILED_BTM_ERR_KEY_MISSING = 121,
  CONNECTION_STATUS_FAILED_BTM_NOT_AUTHENTICATED = 122,
  CONNECTION_STATUS_FAILED_BTM_NOT_ENCRYPTED = 123,
  CONNECTION_STATUS_FAILED_BTM_INSUFFICIENT_ENCRYPT_KEY_SIZE = 124,
  CONNECTION_STATUS_FAILED_BTM_MAX_STATUS_VALUE = 125,
  CONNECTION_STATUS_FAILED_BTM_UNDEFINED = 126,
};

bool ConnectionStatus_IsValid(int value);
extern const uint32_t ConnectionStatus_internal_data_[];
constexpr ConnectionStatus ConnectionStatus_MIN = static_cast<ConnectionStatus>(0);
constexpr ConnectionStatus ConnectionStatus_MAX = static_cast<ConnectionStatus>(126);
constexpr int ConnectionStatus_ARRAYSIZE = 126 + 1;
const std::string& ConnectionStatus_Name(ConnectionStatus value);
template <typename T>
const std::string& ConnectionStatus_Name(T value) {
  static_assert(std::is_same<T, ConnectionStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ConnectionStatus_Name().");
  return ConnectionStatus_Name(static_cast<ConnectionStatus>(value));
}
const std::string& ConnectionStatus_Name(ConnectionStatus value);
bool ConnectionStatus_Parse(absl::string_view name, ConnectionStatus* value);

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace leaudio
}  // namespace bluetooth
}  // namespace android


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::android::bluetooth::leaudio::ContextType> : std::true_type {};
template <>
struct is_proto_enum<::android::bluetooth::leaudio::ConnectionStatus> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_frameworks_2fproto_5flogging_2fstats_2fenums_2fbluetooth_2fleaudio_2fenums_2eproto_2epb_2eh
